{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"eec data file\",\"District_Lookup\",\"Industry Group Lookup\",\"Industry Sub-Category\",\"Province_Lookup\",\"Sub-district_Lookup\",\"TSIC Lookup\",\"Tambon A\",\"Tambon B\",\"Tambon C\",\"Tambon D\",\"Tambon E-F\",\"Tambon H-I\",\"Tambon K\",\"Tambon L\",\"Tambon M\",\"Tambon N-O\",\"Tambon P\",\"Tambon R\",\"Tambon S\",\"Tambon T\",\"Tambon U-V\",\"Tambon W\",\"Tambon Y\",\"Sub-districts (All Thailand)\",\"Missing Tambon\",\"ISIC-BOT Rev#4\",\"Transform eec data file\",\"Data\",\"Address Details\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.119.870.0 (23.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Transform eec data file",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"eec data file\",",
          "    #\"Removed 1st Column\" = Table.RemoveColumns(Source,{\"ลำดับ\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed 1st Column\", each true),",
          "    #\"Added Index\" = Table.AddIndexColumn(#\"Filtered Rows\", \"Index\", 0, 1, Int64.Type),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Index\",{{\"รหัสทะเบียนโรงงาน FID\", Int64.Type}}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"FID factory registration code\", each Number.ToText([รหัสทะเบียนโรงงาน FID],\"0\")),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Custom\",{\"Index\", \"เลขทะเบียนโรงงาน\", \"รหัสทะเบียนโรงงาน FID\", \"FID factory registration code\", \"TSIC\", \"รหัสประเภท\", \"ปีที่ได้รับอนุญาต\", \"ชื่อโรงงาน\", \"ชื่อเจ้าของ\", \"ประกอบกิจการ\", \"เลขที่\", \"หมู่\", \"ซอย\", \"ถนน\", \"ตำบล\", \"อำเภอ\", \"รหัสจังหวัด\", \"จังหวัด\", \"รหัสไปรษณีย์\", \"โทรศัพท์\", \"ค่าอาคาร\", \"ค่าที่ดิน\", \"ค่าเครื่องจักร\", \"เงินทุนหมุนเวียน\", \"เงินลงทุนรวม\", \"ชาย\", \"หญิง\", \"คนงานรวม\", \"แรงม้ารวม\", \"พื้นที่โรงงาน(ตร.ม.)\", \"พื้นที่อาคาร(ตร.ม.)\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"รหัสทะเบียนโรงงาน FID\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"เลขทะเบียนโรงงาน\", \"factory registration number\"}, {\"รหัสประเภท\", \"type code\"}, {\"จำพวก\", \"group\"}, {\"ปีที่ได้รับอนุญาต\", \"licensed year\"}, {\"ชื่อโรงงาน\", \"factory name\"}, {\"ชื่อเจ้าของ\", \"owner name\"}, {\"ประกอบกิจการ\", \"business\"}, {\"เลขที่\", \"number\"}, {\"หมู่\", \"moo\"}, {\"ซอย\", \"soi\"}, {\"ถนน\", \"road\"}, {\"ตำบล\", \"sub-district\"}, {\"อำเภอ\", \"district\"}, {\"รหัสจังหวัด\", \"province code\"}, {\"จังหวัด\", \"province\"}, {\"รหัสไปรษณีย์\", \"post code\"}, {\"โทรศัพท์\", \"telephone\"}, {\"ค่าอาคาร\", \"building value\"}, {\"ค่าที่ดิน\", \"land value\"}, {\"ค่าเครื่องจักร\", \"machine cost\"}, {\"เงินลงทุนรวม\", \"total investment\"}, {\"เงินทุนหมุนเวียน\", \"working capital\"}, {\"ชาย\", \"male\"}, {\"หญิง\", \"female\"}, {\"คนงานรวม\", \"total workers\"}, {\"แรงม้ารวม\", \"total horsepower\"}, {\"พื้นที่โรงงาน(ตร.ม.)\", \"factory area (sq.m.)\"}, {\"พื้นที่อาคาร(ตร.ม.)\", \"Building area (sq.m.)\"}}),",
          "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns\", \"business\", \"business - Copy\"),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"business - Copy\", \"business (EN)\"}, {\"business\", \"business (TH)\"}}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"Index\", \"factory registration number\", \"FID factory registration code\", \"TSIC\", \"type code\", \"group\", \"licensed year\", \"factory name\", \"owner name\", \"business (TH)\", \"business (EN)\", \"number\", \"moo\", \"soi\", \"road\", \"sub-district\", \"district\", \"province code\", \"province\", \"post code\", \"telephone\", \"building value\", \"land value\", \"machine cost\", \"working capital\", \"total investment\", \"male\", \"female\", \"total workers\", \"total horsepower\", \"factory area (sq.m.)\", \"Building area (sq.m.)\"}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Reordered Columns1\",\"ขุดดิน\",\"digging\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ขุดทราย\",\"digging sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"ร่อน คัดขนาดทราย\",\" soil, sifting, sorting sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"ร่อน คัดขนาด ทราย\",\"sifting, grading, sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"บดหรือป่นเครื่องเทศ ผลิตเครื่องแกง และผลิตภัณฑ์อาหารสำเร็จรูปจากเนื้อสัตว์ เช่น น้ำพริกปลาสลิด น้ำพริกปลาทู#(tab)\",\"ground or ground spices production of curry paste and ready-made food products from meat such as gourami fish chili paste, mackerel chili paste\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"ผลิตน้ำมันพืชจากงา และพืชอื่น ๆ\",\"Producing vegetable oil from sesame and other plants\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"ผลิตแป้งมันสำปะหลัง\",\"Production of cassava starch\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"ทำโรงงานเม็ดสาคูเพื่อขายให้กับชุมชนเพื่อนำไปผลิตเป็นอาหารหรือขนมขายให้กับนักท่องเที่ยว\",\"Build a sago seed factory to sell to the community in order to produce food or snacks for sale to tourists.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"ผลิตอาหารสัตว์\",\"feed production\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"ผลิตน้ำแข็งก้อนเล็ก\",\"produce small ice cubes\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"ผลิตถุงมือทุกชนิด\",\"produce all kinds of gloves\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"ทำน้ำแข็งก้อนเล็ก\",\"make small ice cubes\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"ทำน้ำแข็งก้อนเล็ก\",\"make small ice cubes\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"คัดแยกวัสดุที่ไม่ใช้แล้วที่ไม่เป็นของเสียอันตราย\",\"Separate unused materials that are not hazardous waste.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"แปรรูปไม้ ทำวงกบประตู หน้าต่าง และทำเครื่องเรือน เช่น เฟอร์นิเจอร์จากไม้\",\"Processing wood, making door frames, windows, and making furniture such as furniture from wood.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Replaced Value14\",\"ทำวงกบ ประตู หน้าต่างจากไม้แปรรูป\",\"Make door frames, windows from sawn timber.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",\"ผลิตเชื้อเพลิงแข็งอัดเม็ด (wood pellet)\",\"Production of solid fuel pellets (wood pellets)\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value17\" = Table.ReplaceValue(#\"Replaced Value16\",\"ผลิตชิ้นไม้สับจากไม้ที่ปลูกขึ้นโดยเฉพาะ 13 ชนิด ตามมติคณะรัฐมนตรีเพื่อจำหน่าย\",\"Produce wood chips from 13 types of specially planted wood according to the cabinet resolution for sale.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value18\" = Table.ReplaceValue(#\"Replaced Value17\",\"ผลิตก้อนชีวมวลสำหรับใช้ในฟาร์ม และเชื้อเพลิงอัดก้อน/แท่ง\",\"Production of biomass briquettes for use on farms and fuel briquettes/sticks\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value19\" = Table.ReplaceValue(#\"Replaced Value18\",\"ผลิตปุ๋ยอินทรีย์\",\"organic fertilizer production\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value20\" = Table.ReplaceValue(#\"Replaced Value19\",\"แปรรูปไม้เพื่อประดิษฐกรรม ไส ซอย ทำวงกบ ประตูหน้าต่าง และเครื่องเรือนเครื่องใช้จากไม้\",\"Processing wood for invention, planing, alley, making frames, doors, windows and wooden furniture\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value21\" = Table.ReplaceValue(#\"Replaced Value20\",\"อบไม้และอัดน้ำยาไม้\",\"Wood drying and compressing wood solution\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value22\" = Table.ReplaceValue(#\"Replaced Value21\",\"หั่น ตัด บด รีดยาง\",\"Cut, cut, grind, roll rubber\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value23\" = Table.ReplaceValue(#\"Replaced Value22\",\"ผลิตคอนกรีตผสมเสร็จ\",\"Production of ready-mixed concrete\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value24\" = Table.ReplaceValue(#\"Replaced Value23\",\"ทำแป้งมันสำปะหลัง\",\"make cassava flour\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value25\" = Table.ReplaceValue(#\"Replaced Value24\",\"ทำแป้งมัน ได้เดือนละ 30 ตัน\",\"can produce 30 tons of tapioca starch per month\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value26\" = Table.ReplaceValue(#\"Replaced Value25\",\"ทำแผ่นรองสินค้าจากไม้ (พาเลท) ลังไม้\",\"Making product pads from wood (pallets), wooden crates\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value27\" = Table.ReplaceValue(#\"Replaced Value26\",\"ทำน้ำตาลก้อน\",\"make sugar cubes\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value28\" = Table.ReplaceValue(#\"Replaced Value27\",\"ผลิตน้ำแข็งหลอด\",\"tube ice production\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value29\" = Table.ReplaceValue(#\"Replaced Value28\",\"ผลิตไม้พาเลท\",\"produce wooden pallets\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value30\" = Table.ReplaceValue(#\"Replaced Value29\",\"ทำแผ่นรองรับสินค้าจากไม้ ทำลังไม้และอบไม้\",\"Make a sheet to support the product from wood. Making wooden crates and drying wood\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value31\" = Table.ReplaceValue(#\"Replaced Value30\",\"ผลิตเม็ดพลาสติก\",\"plastic pellets\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value32\" = Table.ReplaceValue(#\"Replaced Value31\",\"plastic pelletsและผลิตภัณฑ์พลาสติก เช่น จาน บรรจุภัณฑ์ ฯลฯ\",\"plastic pellets and plastic products such as plates, containers, etc.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value33\" = Table.ReplaceValue(#\"Replaced Value32\",\"digging ล้างทราย\",\"digging wash sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value34\" = Table.ReplaceValue(#\"Replaced Value33\",\"plastic pelletsเกรดบี และบดย่อยพลาสติก\",\"plastic pellets Grade B and crushing plastic\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value35\" = Table.ReplaceValue(#\"Replaced Value34\",\"ทอผ้า\",\"weaving\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value36\" = Table.ReplaceValue(#\"Replaced Value35\",\"ผลิตเฟอร์นิเจอร์\",\"furniture production\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value37\" = Table.ReplaceValue(#\"Replaced Value36\",\"digging ร่อน และคัดกรวดทราย\",\"digging, sifting and sorting gravel\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value38\" = Table.ReplaceValue(#\"Replaced Value37\",\"diggingหรือทราย\",\"digging soil or sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value39\" = Table.ReplaceValue(#\"Replaced Value38\",\"สกรู, น๊อต, สลักเกลียว, แป้นเกลียว, ชิ้นส่วนยานยนต์ และเครื่องมือแพทย์\",\"Screws, Nuts, Bolts, Nuts, Automotive Parts and medical equipment\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value40\" = Table.ReplaceValue(#\"Replaced Value39\",\"ทำยางพาราแผ่น\",\"making rubber sheets\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value41\" = Table.ReplaceValue(#\"Replaced Value40\",\"ผลิตน้ำประปา\",\"tap water production\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value42\" = Table.ReplaceValue(#\"Replaced Value41\",\"ทำลัง ภาชนะรองรับสินค้าและเครื่องเรือนจากไม้\",\"Making crates, containers and furniture from wood\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value43\" = Table.ReplaceValue(#\"Replaced Value42\",\"ทำเครื่องเรือนหรือเครื่องตบแต่งภายในอาคารจากไม้ยางพาราแปรรูป รวมถึงชิ้นส่วนของผลิตภัณฑ์ดังกล่าว\",\"make furniture or decoration in the building from processed rubber wood including parts of such products\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value44\" = Table.ReplaceValue(#\"Replaced Value43\",\"ทำเครื่องเรือนจากไม้ยางพารา\",\"Making furniture from rubber wood\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value45\" = Table.ReplaceValue(#\"Replaced Value44\",\"tap water productionจากน้ำทะเล\",\"tap water production from sea water\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value46\" = Table.ReplaceValue(#\"Replaced Value45\",\"ผลิตชิ้นส่วนละอุปกรณ์เฟอร์นิเจอร์จากไม้\",\"Production of wooden furniture parts and accessories\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value47\" = Table.ReplaceValue(#\"Replaced Value46\",\"ผลิตผลิตภัณฑ์จากโลหะทองเหลืองสำหรับใช้ในการต่อท่อและประกอบเครื่องสุขภัณฑ์\",\"Manufacture products from brass metal for use in pipe connections and assembly of sanitary ware.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value48\" = Table.ReplaceValue(#\"Replaced Value47\",\"ผลิตผลิตภัณฑ์จากโลหะทองเหลือง สำหรับใช้ในการต่อท่อและประกอบเครื่องสุขภัณฑ์\",\"Production of brass products For use in pipe connections and assembly of sanitary ware.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value49\" = Table.ReplaceValue(#\"Replaced Value48\",\"ผลิตและจำหน่ายเฟอร์นิเจอร์\",\"Manufacture and sale of furniture\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value50\" = Table.ReplaceValue(#\"Replaced Value49\",\"ฆ่าและชำแหละชิ้นส่วนสุกร\",\"Slaughter and butcher pigs.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value51\" = Table.ReplaceValue(#\"Replaced Value50\",\"ขุด ตักดิน\",\"dig, shovel\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value52\" = Table.ReplaceValue(#\"Replaced Value51\",\"ฆ่าสัตว์ (ไก่)\",\"Killing animals (chickens)\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value53\" = Table.ReplaceValue(#\"Replaced Value52\",\"ฆ่า ชำแหละไก่ และทำไก๋แช่แข็ง\",\"Killing, butchering chickens and making frozen chicken\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value54\" = Table.ReplaceValue(#\"Replaced Value53\",\"ซํก อบ รีด\",\"Wash, dry, iron\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value55\" = Table.ReplaceValue(#\"Replaced Value54\",\"ชุดดิน ร่อนคัดทราย\",\"Soil set, sifting sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value56\" = Table.ReplaceValue(#\"Replaced Value55\",\"ทำเม็ดสาคู\",\"make sago seed\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value57\" = Table.ReplaceValue(#\"Replaced Value56\",\"ทำไม้อัด\",\"make plywood\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value58\" = Table.ReplaceValue(#\"Replaced Value57\",\"ผสมและบรรจุสารปราบศัตรูพืชและปุ๋ยเคมี\",\"Mix and pack pesticides and chemical fertilizers.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value59\" = Table.ReplaceValue(#\"Replaced Value58\",\"ผลิตสีทาหรือพ่นในโรงงานอุตสาหกรรมก่อสร้าง\",\"Manufacture of paint or spray paint in the construction industry\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value60\" = Table.ReplaceValue(#\"Replaced Value59\",\"ผลิตยางแผ่น (Master Batch) และตัดแผ่นพื้นรองเท้า\",\"Production of rubber sheets (Master Batch) and cut the shoe soles.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value61\" = Table.ReplaceValue(#\"Replaced Value60\",\"ฉีดพลาสติกเป็นชิ้นส่วนอะไหล่ของกระเป๋าเดินทางและผลิตกระเป๋าเดินทาง\",\"Plastic injection for luggage spare parts and luggage production\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value62\" = Table.ReplaceValue(#\"Replaced Value61\",\"ผลิตชิ้นส่วนเรื่องใช้ไฟฟ้า และชิ้นส่วนรถยนต์พลาสติก\",\"Production of electrical parts and plastic auto parts\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value63\" = Table.ReplaceValue(#\"Replaced Value62\",\"ผลิตภัณฑ์ถุงพลาสติก\",\"plastic bag products\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value64\" = Table.ReplaceValue(#\"Replaced Value63\",\"ทำภาชนะบรรจุ เช่น ถุงหรือกระสอบ\",\"Make containers such as bags or sacks.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value65\" = Table.ReplaceValue(#\"Replaced Value64\",\"ผลิตถุงพลาสติก\",\"plastic bag production\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value66\" = Table.ReplaceValue(#\"Replaced Value65\",\"ทำเม็ดพลาสติกจากพลาสติกใช้แล้ว และบดย่อยพลาสติก\",\"Making plastic pellets from used plastic and crushing plastic\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value67\" = Table.ReplaceValue(#\"Replaced Value66\",\"ล้างและบดย่อยเศษพลาสติกและชิ้นส่วน\",\"Wash and shred plastic scraps and parts.\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value68\" = Table.ReplaceValue(#\"Replaced Value67\",\"ผลิตหินเทียม เช่น หินแกรนิต\",\"Artificial stone production such as granite\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Replaced Value69\" = Table.ReplaceValue(#\"Replaced Value68\",\"ผลิตปูนพลาสเตอร์\",\"plaster production\",Replacer.ReplaceText,{\"business (EN)\"}),",
          "    #\"Removed Unused group Column\" = Table.RemoveColumns(#\"Replaced Value69\",{\"group\", \"total horsepower\"})",
          "in",
          "    #\"Removed Unused group Column\""
        ],
        "kind": "m",
        "lineageTag": "494dcf4a-45cb-4d6c-9487-f8d527d92d6f",
        "queryGroup": "Data Source"
      },
      {
        "name": "Tambon A",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(A)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Data0,{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "6d81c64f-b6f7-4dc5-b5ce-f49d55a0ca7a",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon B",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(B)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Data0,{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "ff69058c-0b7d-4ffb-9c64-d5ce2f56e817",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon C",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(C)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "87aba61b-e7ee-4c92-9406-1a747b4c3da9",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon D",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(D)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "03bd2283-c86d-4bc6-8b42-06cfdd897efd",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon E-F",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(E-F)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "7bfe5248-828d-42f5-b61a-0cf730da3771",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon H-I",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(H-I)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "b2f3b898-2e8e-4c99-a902-921e10607eb7",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon K",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(K)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "3969a459-dac6-4ba4-bf96-954b38b3c6f2",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon L",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(L)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "82fda383-d9ce-4c7c-a864-9a214e578b47",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon M",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(M)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Data0,{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "907e2f8e-cc09-445a-90c3-6da03abec7a9",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon N-O",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(N-O)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}, {\"Changwat\", \"Changwat (Province)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "7a163e2d-a0cb-4a7d-a847-fd718137ca69",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon P",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(P)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "e3cfbadd-a6f1-4990-99ff-c619230dfe34",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon R",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(R)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns1\" = Table.RenameColumns(Data0,{{\"District (amphoe)\", \"Amphoe (District)\"}, {\"Province (changwat)\", \"Changwat (Province)\"}, {\"Sub-district (tambon)\", \"Tambon\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "052b625c-fcd4-40bd-a67c-92c36eb532f9",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon S",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(S)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "2959b7d7-6fc2-473e-aa76-929595bace79",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon T",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(T)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "fc8874e8-f5e3-4c8c-8e9a-3a1591887c7c",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon U-V",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(U-V)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "a80d07bb-a372-4c53-a391-589bdc83218b",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon W",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(W)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "b2edf661-bd45-4477-a438-3a0071747770",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Tambon Y",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(Y)\")),",
          "    Data0 = Source{0}[Data],",
          "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "d64f483a-d3dd-4d01-93fc-05be2d8a31bc",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Sub-districts (All Thailand)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.Combine({#\"Tambon A\", #\"Tambon B\", #\"Tambon C\", #\"Tambon D\", #\"Tambon E-F\", #\"Tambon H-I\", #\"Tambon K\", #\"Tambon L\", #\"Tambon M\", #\"Tambon N-O\", #\"Tambon P\", #\"Tambon R\", #\"Tambon S\", #\"Tambon T\", #\"Tambon U-V\", #\"Tambon W\", #\"Tambon Y\"}),",
          "    #\"Added Index\" = Table.AddIndexColumn(Source, \"Index\", 1, 1, Int64.Type),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"Tambon Code\"}}),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Tambon Code\", \"Tambon\", \"ตำบล\", \"Amphoe (District)\", \"อำเภอ\", \"Changwat (Province)\", \"จังหวัด\", \"Region\"}),",
          "    #\"Appended Query\" = Table.Combine({#\"Reordered Columns\", #\"Missing Tambon\"})",
          "in",
          "    #\"Appended Query\""
        ],
        "kind": "m",
        "lineageTag": "170ccb41-1d88-4ac0-88cf-90f3786a5ffc",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      },
      {
        "name": "Missing Tambon",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"rVCxCsJADP0V6ezQ6uRqcRJEcHAoHU4RW9Q7aHVXEar9AbFOIqIogopC+jf5FHM5XZxdQnh5yXsvnmc5Fdu2raJVVYV2KKlByDBfIlwRjghPhA2BrTAS3UDw+ISwR3hxfSCkVAl3AyU7kyhkCmEHfQfAcAmsiXhs+UUj6BBQD4QqUJGxkn29lU8R5nxygXAnXYQ1ryf/N1DSJ0mXDAw/8nDmzAnLH0yv/yKI1RSDLytjTWJtEW4IM8NyA3KnerIfC8W0lZ7qRCn/MOHexHn8mikT0DBmxIi3L5zeuDEv2f3xB/4b\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Tambon Code\" = _t, Tambon = _t, ตำบล = _t, #\"Amphoe (District)\" = _t, อำเภอ = _t, #\"Changwat (Province)\" = _t, จังหวัด = _t, Region = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Tambon Code\", Int64.Type}, {\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "35bee323-234e-4214-b431-bb6b94f1c33a",
        "queryGroup": "Sub District Queries to builld Tambon Table"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Sub District Queries to builld Tambon Table"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Data Source"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Data Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Dimension Queries"
      }
    ],
    "relationships": [
      {
        "name": "4ecf00be-800e-40db-8ec2-0eb3850b9933",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "sub category",
        "fromTable": "Address Details",
        "toCardinality": "many",
        "toColumn": "sub category",
        "toTable": "Industry Sub-Category"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Address Details",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Building area (sq.m.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c1a8187-4fa4-4039-8ab3-0b1045f78a33",
            "sourceColumn": "Building area (sq.m.)",
            "summarizeBy": "sum"
          },
          {
            "name": "Group Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96637e80-ca3f-49d2-b89d-9f73ab6f7018",
            "sourceColumn": "Group Description Thai",
            "summarizeBy": "none"
          },
          {
            "name": "Industry Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a42a9ef-07dd-47f9-bb23-301d005f3a05",
            "sourceColumn": "Industry Group",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Category Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d86e8c7-c539-4c13-b160-e873a42c3390",
            "sourceColumn": "Sub Category Description Thai",
            "summarizeBy": "none"
          },
          {
            "name": "TSIC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdb2d6d1-82bd-4cf0-9dd2-0707feb73e70",
            "sourceColumn": "TSIC",
            "summarizeBy": "none"
          },
          {
            "name": "TSIC Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9a0226f-9150-481e-b6ed-ad9345993498",
            "sourceColumn": "TSIC Description Thai",
            "summarizeBy": "none"
          },
          {
            "name": "building value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "925b583f-b4d2-4b83-938b-680b23a6c6fb",
            "sourceColumn": "building value",
            "summarizeBy": "sum"
          },
          {
            "name": "business (TH)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6d72f05-809b-4cf7-af5d-1098340baeb5",
            "sourceColumn": "business (TH)",
            "summarizeBy": "none"
          },
          {
            "name": "district",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a26cc763-2a54-4d41-899e-657fac8bc9a2",
            "sourceColumn": "district",
            "summarizeBy": "none"
          },
          {
            "name": "factory area (sq.m.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a5d4ca2f-d01a-45fa-9f65-5e5fe0601299",
            "sourceColumn": "factory area (sq.m.)",
            "summarizeBy": "sum"
          },
          {
            "name": "factory name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81a5b12b-0dcb-4dca-a8c6-1d4cc46b458a",
            "sourceColumn": "factory name",
            "summarizeBy": "none"
          },
          {
            "name": "female",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ab4bc8c-4c45-4ce2-81b0-62f17db54945",
            "sourceColumn": "female",
            "summarizeBy": "sum"
          },
          {
            "name": "land value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37275c3f-8439-4850-aa33-8e6100452253",
            "sourceColumn": "land value",
            "summarizeBy": "sum"
          },
          {
            "name": "machine cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3088c17-e304-4f43-bc55-bfe0e6f0d643",
            "sourceColumn": "machine cost",
            "summarizeBy": "sum"
          },
          {
            "name": "male",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b31ca6f1-57da-4634-a215-587da69a7eed",
            "sourceColumn": "male",
            "summarizeBy": "sum"
          },
          {
            "name": "moo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d884d7c2-1d4f-41be-99a2-b8320beb9500",
            "sourceColumn": "moo",
            "summarizeBy": "none"
          },
          {
            "name": "number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bd9f819-8f8b-425a-9d58-1fd539b93bad",
            "sourceColumn": "number",
            "summarizeBy": "none"
          },
          {
            "name": "post code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "728380ff-f2de-48b7-888b-853ca3252117",
            "sourceColumn": "post code",
            "summarizeBy": "none"
          },
          {
            "name": "province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66404f8f-c9fb-47a8-8d1e-93d02f0fa44c",
            "sourceColumn": "province",
            "summarizeBy": "none"
          },
          {
            "name": "road",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1ace85d-06fa-4feb-add3-4b9e2f40907e",
            "sourceColumn": "road",
            "summarizeBy": "none"
          },
          {
            "name": "soi",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "014639e5-4f98-4422-aba5-732bf95e849c",
            "sourceColumn": "soi",
            "summarizeBy": "none"
          },
          {
            "name": "sub category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bf3bf5e-3f67-4fac-9899-d51de01a94d3",
            "sourceColumn": "sub category",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da416a2b-c059-45b2-9c39-c4b9285f9bee",
            "sourceColumn": "sub-district",
            "summarizeBy": "none"
          },
          {
            "name": "telephone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69e0dd6a-93d9-4310-8499-436a70df68fe",
            "sourceColumn": "telephone",
            "summarizeBy": "none"
          },
          {
            "name": "total investment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "638f5f75-2117-42e4-90be-a6f78eaab84b",
            "sourceColumn": "total investment",
            "summarizeBy": "sum"
          },
          {
            "name": "total workers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cdf4c7d3-cb88-41fb-a996-8425819f55ef",
            "sourceColumn": "total workers",
            "summarizeBy": "sum"
          },
          {
            "name": "type code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c47b68fd-0f5e-4d68-8d2b-777f2eca9a3c",
            "sourceColumn": "type code",
            "summarizeBy": "none"
          },
          {
            "name": "working capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70e5fa7f-bf0f-4cfa-ba9c-9da250147b9d",
            "sourceColumn": "working capital",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b6f83f74-20c8-413e-b362-36f1d6e71e00",
        "partitions": [
          {
            "name": "Address Details",
            "mode": "import",
            "queryGroup": "Data Queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Transform eec data file\",    ",
                "    #\"Added Age Column\" = Table.AddColumn(Source, \"Age\", each ",
                "    let",
                "        currentYear = Date.Year(DateTime.LocalNow()),",
                "        buddhistYear = currentYear + 543,",
                "        licensedYearText = Text.From([licensed year]),",
                "        licensedYearFull = Number.FromText(if Text.Length(licensedYearText) = 2 then \"25\" & licensedYearText else licensedYearText),",
                "        age = buddhistYear - licensedYearFull",
                "    in",
                "  age),",
                "    #\"Added 5 Digit TSIC Column\" = Table.AddColumn(#\"Added Age Column\", \"5 Digit TSISC\", each if Text.Length([TSIC]) = 4 then \"0\" & [TSIC] else [TSIC]),",
                "    #\"Changed % Digit TSIC Column Type to Text\" = Table.TransformColumnTypes(#\"Added 5 Digit TSIC Column\",{{\"5 Digit TSISC\", type text}}),",
                "    #\"Removed Old TSIC Column\" = Table.RemoveColumns(#\"Changed % Digit TSIC Column Type to Text\",{\"TSIC\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Old TSIC Column\",{{\"5 Digit TSISC\", \"TSIC\"}}),    ",
                "    #\"Merged TSIC Lookup Query\" = Table.NestedJoin(#\"Renamed Columns\", {\"TSIC\"}, #\"TSIC Lookup\", {\"TSIC\"}, \"TSIC Lookup\", JoinKind.LeftOuter),",
                "    #\"Expanded TSIC Lookup\" = Table.ExpandTableColumn(#\"Merged TSIC Lookup Query\", \"TSIC Lookup\", {\"Group\", \"ISIC Description Thai\", \"sub category\"}, {\"Group\", \"ISIC Description Thai\", \"sub category\"}),",
                "    #\"Renamed Group & ISIC Description Columns\" = Table.RenameColumns(#\"Expanded TSIC Lookup\",{{\"Group\", \"Industry Group\"}, {\"ISIC Description Thai\", \"TSIC Description Thai\"}}),",
                "    #\"Removed Un-needed Columns\" = Table.RemoveColumns(#\"Renamed Group & ISIC Description Columns\",{\"factory registration number\", \"FID factory registration code\", \"licensed year\",\"Index\", \"Age\", \"owner name\", \"business (EN)\", \"province code\"}),",
                "    #\"Merged Industry Group Query\" = Table.NestedJoin(#\"Removed Un-needed Columns\", {\"Industry Group\"}, #\"Industry Group Lookup\", {\"Group\"}, \"Industry Group Lookup\", JoinKind.LeftOuter),",
                "    #\"Expanded Industry Group Lookup\" = Table.ExpandTableColumn(#\"Merged Industry Group Query\", \"Industry Group Lookup\", {\"ISIC Description Thai\"}, {\"ISIC Description Thai\"}),",
                "    #\"Renamed ISIC Description Column\" = Table.RenameColumns(#\"Expanded Industry Group Lookup\",{{\"ISIC Description Thai\", \"Group Description Thai\"}}),",
                "    #\"Merged Industry Sub-Category Lookup Query\" = Table.NestedJoin(#\"Renamed ISIC Description Column\", {\"sub category\"}, #\"Industry Sub-Category\", {\"sub category\"}, \"Industry Sub-Category\", JoinKind.LeftOuter),",
                "    #\"Expanded Industry Sub-Category\" = Table.ExpandTableColumn(#\"Merged Industry Sub-Category Lookup Query\", \"Industry Sub-Category\", {\"ISIC Description Thai\"}, {\"ISIC Description Thai\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded Industry Sub-Category\",{{\"ISIC Description Thai\", \"Sub Category Description Thai\"}}),",
                "    #\"Changed Certain Columns to Numeric Values for Analysis\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"building value\", Int64.Type}, {\"land value\", Int64.Type}, {\"machine cost\", Int64.Type}, {\"working capital\", Int64.Type}, {\"total investment\", Int64.Type}, {\"factory area (sq.m.)\", Int64.Type}, {\"Building area (sq.m.)\", Int64.Type}, {\"male\", Int64.Type}, {\"female\", Int64.Type}, {\"total workers\", Int64.Type}})    ",
                "in",
                "    #\"Changed Certain Columns to Numeric Values for Analysis\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b676ac2d-6e7a-4517-815a-c57a26305e8d",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Building area (sq m.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4d7b72d-3ce3-40e2-b02c-f00a729a1134",
            "sourceColumn": "Building area (sq m.)",
            "summarizeBy": "sum"
          },
          {
            "name": "FID factory registration code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2488196-f217-4540-ada0-e24592939492",
            "sourceColumn": "FID factory registration code",
            "summarizeBy": "none"
          },
          {
            "name": "Industry Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3ce6666-ef0c-45f4-8b0c-2797d3aca130",
            "sourceColumn": "Industry Group",
            "summarizeBy": "none"
          },
          {
            "name": "Machine Cost (M Baht)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4ce42c58-01e9-4d75-9dca-105929aacbbe",
            "sourceColumn": "Machine Cost (M Baht)",
            "summarizeBy": "sum"
          },
          {
            "name": "TSISC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "541d7346-ae56-4635-938d-735e5b8fafe9",
            "sourceColumn": "TSISC",
            "summarizeBy": "none"
          },
          {
            "name": "Total Investment (M Baht)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "df88482f-b5fb-4b1f-be7b-86722a77c520",
            "sourceColumn": "Total Investment (M Baht)",
            "summarizeBy": "sum"
          },
          {
            "name": "Working Capital (M Baht)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8054b373-3d30-4289-8454-b098866ca4bf",
            "sourceColumn": "Working Capital (M Baht)",
            "summarizeBy": "sum"
          },
          {
            "name": "building area (sq Mm)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "204c73e1-a5ef-48c9-8927-5c1a74bead8e",
            "sourceColumn": "building area (sq Mm)",
            "summarizeBy": "sum"
          },
          {
            "name": "building value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b2732b17-f7b2-4bb2-b70f-280ead5587ab",
            "sourceColumn": "building value",
            "summarizeBy": "sum"
          },
          {
            "name": "building value (M Baht)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8ad80a90-4112-466e-be81-27973dd25009",
            "sourceColumn": "building value (M Baht)",
            "summarizeBy": "sum"
          },
          {
            "name": "business (EN)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f2010b2-43cf-4ac0-9bcc-b752f4cc0800",
            "sourceColumn": "business (EN)",
            "summarizeBy": "none"
          },
          {
            "name": "business (TH)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77a24e3c-6704-448a-b0fb-c3ff0695f654",
            "sourceColumn": "business (TH)",
            "summarizeBy": "none"
          },
          {
            "name": "district_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "66e936ec-07e4-463c-8016-61ad7a03a31b",
            "sourceColumn": "district_code",
            "summarizeBy": "sum"
          },
          {
            "name": "factory area (sq Mm)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bd0bd35b-250c-42e5-a13d-def077127fef",
            "sourceColumn": "factory area (sq Mm)",
            "summarizeBy": "sum"
          },
          {
            "name": "factory area (sq.m.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "38a9dfa6-78bd-4085-a166-79d32d75fa89",
            "sourceColumn": "factory area (sq.m.)",
            "summarizeBy": "sum"
          },
          {
            "name": "factory name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6eb0c39f-0881-4b3f-976c-898656084ab2",
            "sourceColumn": "factory name",
            "summarizeBy": "none"
          },
          {
            "name": "factory registration number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fb30e71-9a94-4d4a-8058-5d973fca7316",
            "sourceColumn": "factory registration number",
            "summarizeBy": "none"
          },
          {
            "name": "female",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c16652fe-63b1-4327-8ce4-c6a9466a0e66",
            "sourceColumn": "female",
            "summarizeBy": "sum"
          },
          {
            "name": "land value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67c27bb3-b80a-4ce2-b3d1-a6b1cc0275e3",
            "sourceColumn": "land value",
            "summarizeBy": "sum"
          },
          {
            "name": "land value (M Baht)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8bb5bb79-b70f-41dd-a7b8-648cffb2a9f9",
            "sourceColumn": "land value (M Baht)",
            "summarizeBy": "sum"
          },
          {
            "name": "licensed year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32dd1026-8897-43e0-84f6-83ad1407ffdd",
            "sourceColumn": "licensed year",
            "summarizeBy": "sum"
          },
          {
            "name": "machine cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "933bb0a3-54b5-425c-aea4-a65c35d8a88e",
            "sourceColumn": "machine cost",
            "summarizeBy": "sum"
          },
          {
            "name": "male",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b82d643a-2bb7-41bc-ae75-a4158e975e1a",
            "sourceColumn": "male",
            "summarizeBy": "sum"
          },
          {
            "name": "moo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cf3ef35-6084-460d-86be-58ec82123417",
            "sourceColumn": "moo",
            "summarizeBy": "none"
          },
          {
            "name": "number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "180e90d3-29de-470d-81df-6e4a3a9b5289",
            "sourceColumn": "number",
            "summarizeBy": "none"
          },
          {
            "name": "owner name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59263ccb-c9df-4d65-9e7c-27d5ba3617b3",
            "sourceColumn": "owner name",
            "summarizeBy": "none"
          },
          {
            "name": "post code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d71235c-398b-4615-ac8e-6a21d99abbd7",
            "sourceColumn": "post code",
            "summarizeBy": "none"
          },
          {
            "name": "province code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c63489e6-a876-44d7-8361-2f3bda792f28",
            "sourceColumn": "province code",
            "summarizeBy": "none"
          },
          {
            "name": "road",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e2e3eef-0b7b-45c0-8dba-ad30da9b443b",
            "sourceColumn": "road",
            "summarizeBy": "none"
          },
          {
            "name": "soi",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6f44fae-004a-48c0-8ce6-5ee476688a8f",
            "sourceColumn": "soi",
            "summarizeBy": "none"
          },
          {
            "name": "sub category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "939b6c04-d0b7-4c98-a450-77f43eed7bc5",
            "sourceColumn": "sub category",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bcc46729-917a-4086-af72-2cf447f6d255",
            "sourceColumn": "sub-district code",
            "summarizeBy": "sum"
          },
          {
            "name": "telephone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00646206-b8b6-4da8-b9df-6c03d4177790",
            "sourceColumn": "telephone",
            "summarizeBy": "none"
          },
          {
            "name": "total investment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b3a71f10-3f31-4a9c-a7ec-4448aa37cd90",
            "sourceColumn": "total investment",
            "summarizeBy": "sum"
          },
          {
            "name": "total workers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bdf71985-9e8a-4cf4-b0e1-eee19a92e91a",
            "sourceColumn": "total workers",
            "summarizeBy": "sum"
          },
          {
            "name": "working capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73eafe99-4508-4146-b050-9e672c6ad2b9",
            "sourceColumn": "working capital",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d2edb2f4-4f2a-41a5-b4b8-94c2ab876634",
        "partitions": [
          {
            "name": "Data",
            "mode": "import",
            "queryGroup": "Data Queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Transform eec data file\",",
                "    #\"Added Custom\" = Table.AddColumn(Source, \"5 Digit TSISC\", each if Text.Length([TSIC]) = 4 then \"0\" & [TSIC] else [TSIC]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"5 Digit TSISC\", type text}, {\"Building area (sq.m.)\", Int64.Type}, {\"factory area (sq.m.)\", Int64.Type}, {\"total workers\", Int64.Type}, {\"female\", Int64.Type}, {\"male\", Int64.Type}, {\"total investment\", type number}, {\"working capital\", type number}, {\"machine cost\", type number}, {\"land value\", type number}, {\"building value\", type number}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"5 Digit TSISC\"}, #\"TSIC Lookup\", {\"TSIC\"}, \"TSIC Lookup\", JoinKind.LeftOuter),",
                "    #\"Expanded TSIC Lookup\" = Table.ExpandTableColumn(#\"Merged Queries\", \"TSIC Lookup\", {\"Group\", \"sub category\"}, {\"Group\", \"sub category\"}),",
                "    #\"Renamed Group Column\" = Table.RenameColumns(#\"Expanded TSIC Lookup\",{{\"Group\", \"Industry Group\"}}),",
                "    #\"Removed TSIC Column\" = Table.RemoveColumns(#\"Renamed Group Column\",{\"TSIC\"}),",
                "    #\"Renamed 5 Digit TSIC Column\" = Table.RenameColumns(#\"Removed TSIC Column\",{{\"5 Digit TSISC\", \"TSISC\"}}),",
                "    #\"Merged Districts\" = Table.NestedJoin(#\"Renamed 5 Digit TSIC Column\", {\"district\"}, #\"District_Lookup\", {\"district (TH)\"}, \"District_Lookup\", JoinKind.LeftOuter),",
                "    #\"Expanded District_Lookup\" = Table.ExpandTableColumn(#\"Merged Districts\", \"District_Lookup\", {\"district_code\"}, {\"district_code\"}),",
                "    #\"Merged Sub-district Lookup\" = Table.NestedJoin(#\"Expanded District_Lookup\", {\"sub-district\"}, #\"Sub-district_Lookup\", {\"sub-district (TH)\"}, \"Sub-district_Lookup\", JoinKind.LeftOuter),",
                "    #\"Expanded Sub-district_Lookup\" = Table.ExpandTableColumn(#\"Merged Sub-district Lookup\", \"Sub-district_Lookup\", {\"sub-district code\"}, {\"sub-district code\"}),",
                "    ",
                "    ",
                "    ",
                "    #\"Removed sub-district,district & Province columns\" = Table.RemoveColumns(#\"Expanded Sub-district_Lookup\",{\"sub-district\", \"district\", \"province\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed sub-district,district & Province columns\",{\"Index\", \"factory registration number\", \"FID factory registration code\", \"type code\", \"licensed year\", \"factory name\", \"owner name\", \"business (TH)\", \"business (EN)\", \"number\", \"moo\", \"soi\", \"road\", \"district_code\", \"sub-district code\", \"province code\", \"post code\", \"telephone\", \"building value\", \"land value\", \"machine cost\", \"working capital\", \"total investment\", \"male\", \"female\", \"total workers\", \"factory area (sq.m.)\", \"Building area (sq.m.)\", \"TSISC\", \"Industry Group\", \"sub category\"}),    ",
                "    #\"Removed Index and Type Code\" = Table.RemoveColumns(#\"Reordered Columns\",{\"Index\", \"type code\"}),",
                "    #\"Added Age Column\" = Table.AddColumn(#\"Removed Index and Type Code\", \"Age\", each ",
                "    let",
                "        currentYear = Date.Year(DateTime.LocalNow()),",
                "       buddhistYear = currentYear + 543,",
                "        licensedYearText = Text.From([licensed year]),",
                "        licensedYearFull = Number.FromText(if Text.Length(licensedYearText) = 2 then \"25\" & licensedYearText else licensedYearText),",
                "            age = buddhistYear - licensedYearFull",
                "    in",
                "    age),",
                "    #\"Changed Age Column to Integer\" = Table.TransformColumnTypes(#\"Added Age Column\",{{\"Age\", Int64.Type}}),",
                "    #\"Added Ratio column\" = Table.AddColumn(#\"Changed Age Column to Integer\", \"Ratio\", each if [#\"Building area (sq.m.)\"] = null or [#\"factory area (sq.m.)\"] = null then 0 else if [#\"Building area (sq.m.)\"] = 0 or [#\"factory area (sq.m.)\"] = 0 then 0 else [#\"Building area (sq.m.)\"] /[#\"factory area (sq.m.)\"]),",
                "    #\"Changed Ratio Column to Decimal Number\" = Table.TransformColumnTypes(#\"Added Ratio column\",{{\"Ratio\", type number}}),",
                "    #\"Added Conditional Column to Detect Large Ratio Figures\" = Table.AddColumn(#\"Changed Ratio Column to Decimal Number\", \"Adjusted Building area (sq m.)\", each if [Ratio] > 1000 then 0 else if [Ratio] = 0 then 0 else [#\"Building area (sq.m.)\"]),",
                "    #\"Removed Building Area (sq m.) and Ratio Columns\" = Table.RemoveColumns(#\"Added Conditional Column to Detect Large Ratio Figures\",{\"Building area (sq.m.)\", \"Ratio\"}),",
                "    #\"changed Adjusted Building Area (sq m.) to Building area (sq m.)\" = Table.RenameColumns(#\"Removed Building Area (sq m.) and Ratio Columns\",{{\"Adjusted Building area (sq m.)\", \"Building area (sq m.)\"}}),",
                "    #\"Changed Building Area (sq m.) to Integer Type\" = Table.TransformColumnTypes(#\"changed Adjusted Building Area (sq m.) to Building area (sq m.)\",{{\"Building area (sq m.)\", Int64.Type}}),",
                "    #\"Added New Column Building Area (sq Mm)\" = Table.AddColumn(#\"Changed Building Area (sq m.) to Integer Type\", \"building area (sq Mm)\", each if [#\"Building area (sq m.)\"] > 0 then [#\"Building area (sq m.)\"] / 1000000 else 0),",
                "    #\"Changed Building Area (sq Mm) to Decimal Number\" = Table.TransformColumnTypes(#\"Added New Column Building Area (sq Mm)\",{{\"building area (sq Mm)\", type number}}),",
                "    #\"Added New Column Factory Area (sq Mm)\" = Table.AddColumn(#\"Changed Building Area (sq Mm) to Decimal Number\", \"factory area (sq Mm)\", each if [#\"factory area (sq.m.)\"] = null then 0 else if [#\"factory area (sq.m.)\"] > 0 then [#\"factory area (sq.m.)\"] / 1000000 else 0),",
                "    #\"Changed Factory Area (sq Mm) to Decimal Number\" = Table.TransformColumnTypes(#\"Added New Column Factory Area (sq Mm)\",{{\"factory area (sq Mm)\", type number}}),",
                "    #\"Added Building Value (M Baht)\" = Table.AddColumn(#\"Changed Factory Area (sq Mm) to Decimal Number\", \"building value (M Baht)\", each if [building value] = null then 0 else if [building value] > 0 then [building value] / 1000000 else 0),",
                "    #\"Added Land Value (M Baht) Column\" = Table.AddColumn(#\"Added Building Value (M Baht)\", \"land value (M Baht)\", each if [land value] = null then 0 else if [land value] > 0 then [land value] / 1000000 else 0),",
                "    #\"Changed Building value (M Baht) and Land Value (M Baht)  Columns to Decimal Number\" = Table.TransformColumnTypes(#\"Added Land Value (M Baht) Column\",{{\"building value (M Baht)\", type number}, {\"land value (M Baht)\", type number}}),",
                "    #\"Added Machine Cost (M Baht) Column\" = Table.AddColumn(#\"Changed Building value (M Baht) and Land Value (M Baht)  Columns to Decimal Number\", \"Machine Cost (M Baht)\", each if [machine cost] = null then 0 else if [machine cost] > 0 then [machine cost] / 1000000 else 0),",
                "    #\"Changed Machine Cost (M Baht) to Decimal Number\" = Table.TransformColumnTypes(#\"Added Machine Cost (M Baht) Column\",{{\"Machine Cost (M Baht)\", type number}}),",
                "    #\"Added Working Capital Number (M Baht)\" = Table.AddColumn(#\"Changed Machine Cost (M Baht) to Decimal Number\", \"Working Capital (M Baht)\", each if [working capital] = null then 0 else if [working capital] > 0 then [working capital] / 1000000 else 0),",
                "    #\"Added Total Investment (M Baht)\" = Table.AddColumn(#\"Added Working Capital Number (M Baht)\", \"Total Investment (M Baht)\", each if [total investment] = null then null else if [total investment] > 0 then [total investment] / 1000000 else 0),",
                "    #\"Changed Working Capital (M Baht) and Total Investment (M Baht) to Decimal Number\" = Table.TransformColumnTypes(#\"Added Total Investment (M Baht)\",{{\"Working Capital (M Baht)\", type number}, {\"Total Investment (M Baht)\", type number}, {\"licensed year\", Int64.Type}})",
                "in",
                "    #\"Changed Working Capital (M Baht) and Total Investment (M Baht) to Decimal Number\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_672b22fe-0c56-4d42-8812-cd012a05872f",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a7669f2c-c128-405d-b678-d0199a2a076a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0280b95b-f3be-45d5-bb1a-adb38e164af7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "920e74e9-b4d7-4b28-9c0c-92a2e0216024",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "80c1e8a6-6cec-4f04-b912-308a24d9c509",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c96c8627-2ea0-43e4-b160-f98ca426ce8f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "93728779-2160-4e2f-97be-4fe32e2a042d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba7a0ead-0ff2-45a2-b7e6-88eb4761b472",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "08d041e8-bed7-4ae1-9c0c-8ceee9b9b9f6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8c9ceffc-5024-4d44-8ebd-ec56005b8a9b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6d0d783d-4676-44fc-81e5-7a7189c82c71",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dbbee82a-0ecc-4752-acc7-43348c2c2c1d",
                "ordinal": 3
              }
            ],
            "lineageTag": "001e648d-6bba-402e-a4a9-f984769070c3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "7abf2252-8e38-4d6e-83ad-2e23b4b09036",
        "partitions": [
          {
            "name": "DateTableTemplate_672b22fe-0c56-4d42-8812-cd012a05872f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "District_Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "district",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c64565fb-b0d9-4802-9d30-51f5fb476525",
            "sourceColumn": "district",
            "summarizeBy": "none"
          },
          {
            "name": "district (EN)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bec599f4-6e84-4f31-86f2-4f5a55921cb9",
            "sourceColumn": "district (EN)",
            "summarizeBy": "none"
          },
          {
            "name": "district (TH)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbf158ac-96bf-455e-8d05-6cbd13f63534",
            "sourceColumn": "district (TH)",
            "summarizeBy": "none"
          },
          {
            "name": "district_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cf6541e7-d3db-4f01-a115-ab9571cf0764",
            "sourceColumn": "district_code",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "90efea27-d6d9-4b8d-8549-e0f1e9cece7e",
        "partitions": [
          {
            "name": "District_Lookup",
            "mode": "import",
            "queryGroup": "Dimension Queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Transform eec data file\",",
                "    #\"Removed Columns1\" = Table.RemoveColumns(Source,{\"Index\", \"factory registration number\", \"FID factory registration code\", \"TSIC\", \"type code\", \"licensed year\", \"factory name\", \"owner name\", \"business (TH)\", \"business (EN)\", \"number\", \"moo\", \"soi\", \"road\", \"sub-district\", \"province code\", \"province\", \"post code\", \"telephone\", \"building value\", \"land value\", \"machine cost\", \"working capital\", \"total investment\", \"male\", \"female\", \"total workers\", \"factory area (sq.m.)\", \"Building area (sq.m.)\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns1\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"district_index\"}, {\"district\", \"district (TH)\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns\", \"district (TH)\", \"district (TH) - Copy\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Duplicated Column\",{\"district (TH)\", \"district (TH) - Copy\", \"district_index\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Reordered Columns\",{{\"district (TH) - Copy\", \"district (EN)\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns2\",\"เกาะจันทร์\",\"Koh Chan\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"เกาะสีชัง\",\"Koh Sichang\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"บ่อทอง\",\"Bo Thong\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"บางละมุง\",\"Bang Lamung\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"บ้านบึง\",\"Ban Bueng\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"พนัสนิคม\",\"Phanat Nikhom\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"พานทอง\",\"Phan Thong\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"เมืองชลบุรี\",\"Chonburi\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"ศรีราชา\",\"Sriracha\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"สัตหีบ\",\"Sattahip\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"หนองใหญ่\",\"Nong Yai\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"แกลง\",\"Klaeng\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"เขาชะเมา\",\"Khao Chamao\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"นิคมพัฒนา\",\"Nikhom Phatthana\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"บ้านค่าย\",\"Baan Khai\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Replaced Value14\",\"บ้านฉาง\",\"Ban Chang\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",\"Baan Khai\",\"Ban Khai\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value17\" = Table.ReplaceValue(#\"Replaced Value16\",\"ปลวกแดง\",\"Pluak Daeng\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value18\" = Table.ReplaceValue(#\"Replaced Value17\",\"เมืองระยอง\",\"Rayong\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value19\" = Table.ReplaceValue(#\"Replaced Value18\",\"วังจันทร์\",\"Wang Chan\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value20\" = Table.ReplaceValue(#\"Replaced Value19\",\"คลองเขื่อน\",\"Khlong Khuean\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value21\" = Table.ReplaceValue(#\"Replaced Value20\",\"ท่าตะเกียบ\",\"Tha Takiap\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value22\" = Table.ReplaceValue(#\"Replaced Value21\",\"บางคล้า\",\"Bang Khla\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value23\" = Table.ReplaceValue(#\"Replaced Value22\",\"บางน้ำเปรี้ยว\",\"Bang Nam Priao\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value24\" = Table.ReplaceValue(#\"Replaced Value23\",\"บางปะกง\",\"Bang Pakong\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value25\" = Table.ReplaceValue(#\"Replaced Value24\",\"บ้านโพธิ์\",\"Ban Pho\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value26\" = Table.ReplaceValue(#\"Replaced Value25\",\"แปลงยาว\",\"Plaeng Yao\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value27\" = Table.ReplaceValue(#\"Replaced Value26\",\"พนมสารคาม\",\"Phanom Sarakham\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value28\" = Table.ReplaceValue(#\"Replaced Value27\",\"เมืองฉะเชิงเทรา\",\"Chachoengsao\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value29\" = Table.ReplaceValue(#\"Replaced Value28\",\"ราชสาส์น\",\"Ratchasan\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Replaced Value30\" = Table.ReplaceValue(#\"Replaced Value29\",\"สนามชัยเขต\",\"Sanam Chai Khet\",Replacer.ReplaceText,{\"district (EN)\"}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Replaced Value30\",{{\"district_index\", \"district_code\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns3\",{\"district_code\", \"district (TH)\", \"district (EN)\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Reordered Columns1\", \"district\", each [#\"district (TH)\"] & \" / \" & [#\"district (EN)\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"district\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ISIC-BOT Rev#4",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Activity / Activity BOT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1edd9e06-3051-4ea9-a79a-12503e1e4af4",
            "sourceColumn": "Activity / Activity BOT",
            "summarizeBy": "none"
          },
          {
            "name": "Adjusted TSIC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc6f9535-bab2-4548-99fe-c00d1443d438",
            "sourceColumn": "Adjusted TSIC",
            "summarizeBy": "none"
          },
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92cebe25-92ef-41cc-a774-c8213d85a3c7",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Goods Production",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35298bb0-702e-4f83-8bdc-23e25ac07bb1",
            "sourceColumn": "Goods Production",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84aea47c-4ba6-47c1-bef3-d792789dbdfe",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          },
          {
            "name": "ISIC Description English",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2382a589-8ce9-4519-b406-8f7999c49704",
            "sourceColumn": "ISIC Description English",
            "summarizeBy": "none"
          },
          {
            "name": "ISIC Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b91e1ae-8c4a-4db9-9c2e-7547e7c74277",
            "sourceColumn": "ISIC Description Thai",
            "summarizeBy": "none"
          },
          {
            "name": "Parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "098047cf-2d17-4035-b9be-e7fe56617096",
            "sourceColumn": "Parent",
            "summarizeBy": "none"
          },
          {
            "name": "Retail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee17ec4c-59d8-43d4-8de4-fee98e9b1e4e",
            "sourceColumn": "Retail",
            "summarizeBy": "none"
          },
          {
            "name": "Section",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6619a26e-5019-4f98-bed6-eceb29d2b920",
            "sourceColumn": "Section",
            "summarizeBy": "none"
          },
          {
            "name": "Service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b10fb89-6b7b-4be6-9f16-b06bfa7aa385",
            "sourceColumn": "Service",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Section",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24045689-9062-4493-9368-61a85f0ead20",
            "sourceColumn": "Sub-Section",
            "summarizeBy": "none"
          },
          {
            "name": "Wholesale",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "797d2fde-8b62-4a5a-8374-64dad40f8179",
            "sourceColumn": "Wholesale",
            "summarizeBy": "none"
          },
          {
            "name": "sub activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e3b4707-67ac-413b-b70f-31dee40019f7",
            "sourceColumn": "sub activity",
            "summarizeBy": "none"
          },
          {
            "name": "sub category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1899b3a7-1320-402e-94de-1c466327e9e6",
            "sourceColumn": "sub category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a2055582-f626-48e4-baec-023383a6982f",
        "partitions": [
          {
            "name": "ISIC-BOT Rev#4",
            "mode": "import",
            "queryGroup": "Data Source",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"http://pub.nstda.or.th/gov-dx/wp-content/uploads/2022/01/ISIC-BOT-Code-Rev-4-add-mark-SME_551225.xls\"), null, true),",
                "    #\"ISIC-BOT Rev#1\" = Source{[Name=\"ISIC-BOT Rev#4\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"ISIC-BOT Rev#1\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}}),",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Changed Type\",1),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Top Rows\", [PromoteAllScalars=true]),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Promoted Headers\",{{\"Column19\", \"Retail\"}, {\"Column18\", \"Wholesale\"}, {\"Column17\", \"Service\"}, {\"ประเภทกิจการวิสาหกิจ#(lf)ตาม พรบ. ส่งเสริมวิสาหกิจขนาดกลางและขนาดย่อม พ.ศ. 2543\", \"Goods Production\"}}),",
                "    #\"Removed Top Rows1\" = Table.Skip(#\"Renamed Columns1\",1),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Top Rows1\",{{\"รหัส\", \"Code\"}, {\"รายละเอียดกิจกรรมทางเศรษฐกิจ\", \"Description 1\"}, {\"Column3\", \"Description 2\"}, {\"Column4\", \"Description 3\"}, {\"Column5\", \"Description 4\"}, {\"Column6\", \"Description 5\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",null,\"\",Replacer.ReplaceValue,{\"Description 1\", \"Description 2\", \"Description 3\", \"Description 4\", \"Description 5\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Replaced Value\", \"ISIC Description Thai\", each [Description 1] & [Description 2] & [Description 3] & [Description 4] & [Description 5]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"ISIC Description Thai\", type text}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Changed Type1\",{\"Code\", \"Description 1\", \"Description 2\", \"Description 3\", \"Description 4\", \"Description 5\", \"ISIC Description Thai\", \"รายงานข้อมูล DMS\", \"หมวด\", \"หมวดย่อย\", \"หมู่\", \"หมู่ย่อย\", \"กิจกรรม / กิจกรรม ธปท.\", \"กิจกรรมย่อย#(lf)ธปท.\", \"ISIC Description\", \"Parent\", \"Goods Production\", \"Service\", \"Wholesale\", \"Retail\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"รายงานข้อมูล DMS\"}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Removed Columns\", \"Adjusted TSIC\", each if Text.Contains([Code],\"00000\") then Text.Start([Code],5) else Text.Middle([Code],1,5)),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Adjusted TSIC\", type text}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Changed Type2\",{\"Code\", \"Description 1\", \"Description 2\", \"Description 3\", \"Description 4\", \"Description 5\", \"ISIC Description Thai\", \"หมวด\", \"หมวดย่อย\", \"หมู่\", \"หมู่ย่อย\", \"กิจกรรม / กิจกรรม ธปท.\", \"Adjusted TSIC\", \"กิจกรรมย่อย#(lf)ธปท.\", \"ISIC Description\", \"Parent\", \"Goods Production\", \"Service\", \"Wholesale\", \"Retail\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Reordered Columns1\",{{\"กิจกรรมย่อย#(lf)ธปท.\", \"sub activity\"}, {\"ISIC Description\", \"ISIC Description English\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns2\",{\"Description 1\", \"Description 2\", \"Description 3\", \"Description 4\", \"Description 5\"}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Removed Columns1\",{{\"หมวด\", \"Group\"}, {\"หมวดย่อย\", \"sub category\"}, {\"หมู่\", \"Section\"}, {\"หมู่ย่อย\", \"Sub-Section\"}, {\"กิจกรรม / กิจกรรม ธปท.\", \"Activity / Activity BOT\"}}),",
                "    #\"Removed Bottom Rows\" = Table.RemoveLastN(#\"Renamed Columns3\",2)",
                "in",
                "    #\"Removed Bottom Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Industry Group Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e9c29dc-cab5-4047-97dd-760ea6dfe262",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a7d37a9-28d9-41b8-aa9c-0c769bb78ff3",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          },
          {
            "name": "Group Description English",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3811e7ee-117c-4ccd-8772-5683178f094e",
            "sourceColumn": "Group Description English",
            "summarizeBy": "none"
          },
          {
            "name": "Group Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccd52371-7708-4f4c-bca2-20f3ddc55b69",
            "sourceColumn": "Group Description Thai",
            "summarizeBy": "none"
          },
          {
            "name": "ISIC Description English",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "275ed867-c898-49df-a5a2-fb02d1c9fda3",
            "sourceColumn": "ISIC Description English",
            "summarizeBy": "none"
          },
          {
            "name": "ISIC Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d7ae154-7909-4e21-8e59-9320a5be2ed8",
            "sourceColumn": "ISIC Description Thai",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f36703d6-8195-47f4-b488-a1074e31398d",
        "partitions": [
          {
            "name": "Industry Group Lookup",
            "mode": "import",
            "queryGroup": "Dimension Queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"TSIC Lookup\",",
                "    #\"Split Column by Character Transition\" = Table.SplitColumn(Source, \"TSIC\", Splitter.SplitTextByCharacterTransition((c) => not List.Contains({\"0\"..\"9\"}, c), {\"0\"..\"9\"}), {\"TSIC.1\", \"TSIC.2\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Split Column by Character Transition\", each ([TSIC.2] = \"0000\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"TSIC.2\", \"TSIC.1\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Columns\",{\"Code\", \"Group\", \"ISIC Description Thai\", \"ISIC Description English\", \"sub category\", \"Section\", \"Sub-Section\", \"Parent\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns\",{\"sub category\", \"Section\", \"Sub-Section\",  \"Parent\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns1\", \"Group Description Thai\", each [Group] & \": \" & [ISIC Description Thai]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Group Description Thai\", type text}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type\", \"Group Description English\", each [Group] & \": \" &[ISIC Description English])",
                "in",
                "    #\"Added Custom1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Industry Sub-Category",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "045bfbe2-ceff-4fd4-8a49-11299b12e7bd",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b140bb3-e42c-4ba2-bdc5-9ac761a75b8f",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          },
          {
            "name": "ISIC Description English",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ba0849c-0f5a-4be6-a8b7-ff1a5b8259e1",
            "sourceColumn": "ISIC Description English",
            "summarizeBy": "none"
          },
          {
            "name": "ISIC Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6fd7994-612f-43d7-adb2-096a2b9e8ed1",
            "sourceColumn": "ISIC Description Thai",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Category Description English",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83585f25-83eb-4cdd-8bfa-7cf5b3f67cd0",
            "sourceColumn": "Sub Category Description English",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Category Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4e53d47-275d-46f2-8704-78be7aa3ac87",
            "sourceColumn": "Sub Category Description Thai",
            "summarizeBy": "none"
          },
          {
            "name": "TSIC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6fdf962-3eaf-4a50-a509-35f1e7332ba5",
            "sourceColumn": "TSIC",
            "summarizeBy": "none"
          },
          {
            "name": "sub category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2971d450-c289-4f63-b0b0-32ade3814a2a",
            "sourceColumn": "sub category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "24eac390-19d9-4530-9b83-cc074379675c",
        "partitions": [
          {
            "name": "Industry Sub-Category",
            "mode": "import",
            "queryGroup": "Dimension Queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"TSIC Lookup\",",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Section\", \"Sub-Section\", \"Parent\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Columns\",{\"sub category\", \"Code\", \"TSIC\", \"ISIC Description Thai\", \"ISIC Description English\", \"Group\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Reordered Columns\", each [sub category] <> \"0\"),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Filtered Rows1\", {\"sub category\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Duplicates\", \"Sub Category Description Thai\", each [sub category] & \" : \" &[ISIC Description Thai]),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Sub Category Description English\", each [sub category] & \" : \" &[ISIC Description English]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Sub Category Description Thai\", type text}, {\"Sub Category Description English\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Province_Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba2b4521-2826-49d7-aa91-1257a1c70957",
            "sourceColumn": "Province",
            "summarizeBy": "none"
          },
          {
            "name": "province (EN)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d72a3cb-8138-4ef1-90c1-dc4748445a0d",
            "sourceColumn": "province (EN)",
            "summarizeBy": "none"
          },
          {
            "name": "province (TH)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbca7724-e271-42b2-a0c2-dde31d240b8b",
            "sourceColumn": "province (TH)",
            "summarizeBy": "none"
          },
          {
            "name": "province code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "636140ec-8e66-49e4-b528-4c3da301b3db",
            "sourceColumn": "province code",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "beeed8cb-ad80-41f5-8f4a-dc9a5c1d22de",
        "partitions": [
          {
            "name": "Province_Lookup",
            "mode": "import",
            "queryGroup": "Dimension Queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Transform eec data file\",                    ",
                "    #\"Removed Duplicates\" = Table.Distinct(Source, {\"province code\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Removed Duplicates\",{\"Index\", \"factory registration number\", \"FID factory registration code\", \"TSIC\", \"type code\", \"licensed year\", \"factory name\", \"owner name\", \"business (TH)\", \"business (EN)\", \"number\", \"moo\", \"soi\", \"road\", \"sub-district\", \"district\", \"post code\", \"telephone\", \"building value\", \"land value\", \"machine cost\", \"working capital\", \"total investment\", \"male\", \"female\", \"total workers\", \"factory area (sq.m.)\", \"Building area (sq.m.)\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns1\",{{\"province\", \"province (TH)\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns\", \"province (TH)\", \"province (TH) - Copy\"),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Duplicated Column\",{{\"province (TH) - Copy\", \"province (EN)\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns2\",\"ชลบุรี\",\"Chonburi\",Replacer.ReplaceText,{\"province (EN)\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ระยอง\",\"Rayong\",Replacer.ReplaceText,{\"province (EN)\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"ฉะเชิงเทรา\",\"Chachoengsao\",Replacer.ReplaceText,{\"province (EN)\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Replaced Value2\", \"Province\", each [#\"province (TH)\"] & \" / \" & [#\"province (EN)\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Province\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sub-district_Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sub-district",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1224a5d5-0bb4-456c-850f-96bf174688f4",
            "sourceColumn": "sub-district",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district (EN)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "975792c6-81a6-4310-958c-9390fc9da893",
            "sourceColumn": "sub-district (EN)",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district (TH)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ee8dbdb-1730-4195-9762-202364069d51",
            "sourceColumn": "sub-district (TH)",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0fcbefc4-24f2-4db2-a36c-3e8b4c8c3544",
            "sourceColumn": "sub-district code",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b14da4be-87fa-4129-b6f1-c0e419a0a686",
        "partitions": [
          {
            "name": "Sub-district_Lookup",
            "mode": "import",
            "queryGroup": "Dimension Queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Sub-districts (All Thailand)\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Region] = \"East\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Amphoe (District)\", \"อำเภอ\", \"Changwat (Province)\", \"จังหวัด\", \"Region\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\", {\"ตำบล\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"Tambon\", \"Sub-district (EN)\"}, {\"ตำบล\", \"Sub-district (TH)\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Tambon Code\", \"Sub-district (TH)\", \"Sub-district (EN)\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Tambon Code\", \"sub-district code\"}, {\"Sub-district (TH)\", \"sub-district (TH)\"}, {\"Sub-district (EN)\", \"sub-district (EN)\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"sub-district\", each [#\"sub-district (TH)\"] & \" / \" & [#\"sub-district (EN)\"])",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TSIC Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bceb88e4-3b7d-485a-a893-d3058a1efb84",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59a65edc-2148-4142-8e4b-48e79031e8dd",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          },
          {
            "name": "ISIC Description English",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "218ccd48-36d3-4da9-a0ba-e64ee9c8059f",
            "sourceColumn": "ISIC Description English",
            "summarizeBy": "none"
          },
          {
            "name": "ISIC Description Thai",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07096cf1-865e-4f91-810f-2de5a269d94c",
            "sourceColumn": "ISIC Description Thai",
            "summarizeBy": "none"
          },
          {
            "name": "Parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76bbc7b7-f1f3-4d89-8ca7-96466a4d7d3c",
            "sourceColumn": "Parent",
            "summarizeBy": "none"
          },
          {
            "name": "Section",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cced031e-8cfb-4688-bcaf-7587892871c4",
            "sourceColumn": "Section",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Section",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51d95f3e-72aa-4141-b480-f5539ecda635",
            "sourceColumn": "Sub-Section",
            "summarizeBy": "none"
          },
          {
            "name": "TSIC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03420e22-cce0-4263-a606-35b56b274efc",
            "sourceColumn": "TSIC",
            "summarizeBy": "none"
          },
          {
            "name": "sub category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be435809-9a97-4662-9b94-0f1f98f00400",
            "sourceColumn": "sub category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d97371b1-f1cd-4288-befe-e7f2c57c543f",
        "partitions": [
          {
            "name": "TSIC Lookup",
            "mode": "import",
            "queryGroup": "Dimension Queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"ISIC-BOT Rev#4\",",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Code\", type text}, {\"Activity / Activity BOT\", type text}, {\"sub activity\", type text}, {\"ISIC Description Thai\", type text}, {\"Sub-Section\", type text}, {\"Section\", type text}, {\"sub category\", type text}, {\"Group\", type text}, {\"ISIC Description English\", type text}, {\"Parent\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Service\", \"Wholesale\", \"Retail\", \"Goods Production\"}),",
                "    #\"Filled Down\" = Table.FillDown(#\"Removed Columns\",{\"Group\", \"sub category\", \"Section\", \"Sub-Section\", \"Activity / Activity BOT\"}),",
                "    #\"Replaced with null values\" = Table.ReplaceValue(#\"Filled Down\",\"-\",null,Replacer.ReplaceValue,{\"Code\", \"ISIC Description Thai\", \"Group\", \"sub category\", \"Section\", \"Sub-Section\", \"Activity / Activity BOT\", \"Adjusted TSIC\", \"sub activity\", \"ISIC Description English\", \"Parent\"}),    ",
                "    #\"Removed Activity Column\" = Table.RemoveColumns(#\"Replaced with null values\",{\"Activity / Activity BOT\"}),",
                "    #\"Changed Adjusted TSIC Type\" = Table.TransformColumnTypes(#\"Removed Activity Column\",{{\"Adjusted TSIC\", type text}}),",
                "    #\"Renamed Adjusted TSIC Column\" = Table.RenameColumns(#\"Changed Adjusted TSIC Type\",{{\"Adjusted TSIC\", \"TSIC\"}}),",
                "    #\"Removed Bottom Rows\" = Table.RemoveLastN(#\"Renamed Adjusted TSIC Column\",2),",
                "    #\"Removed Duplicates in TSIC Column\" = Table.Distinct(#\"Removed Bottom Rows\", {\"TSIC\"}),    ",
                "    #\"Removed sub activity Column\" = Table.RemoveColumns(#\"Removed Duplicates in TSIC Column\",{\"sub activity\"}),",
                "    #\"Changed All Columns to Text\" = Table.TransformColumnTypes(#\"Removed sub activity Column\",{{\"Code\", type text}, {\"TSIC\", type text}, {\"ISIC Description Thai\", type text}, {\"ISIC Description English\", type text}, {\"Group\", type text}, {\"sub category\", type text}, {\"Section\", type text}, {\"Sub-Section\", type text}, {\"Parent\", type text}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed All Columns to Text\",{{\"TSIC\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "eec data file",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "TSIC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58300ad4-f7ae-400b-8cab-0288f3c48118",
            "sourceColumn": "TSIC",
            "summarizeBy": "none"
          },
          {
            "name": "คนงานรวม",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "326bb556-f3ba-4709-b083-b2b00235dbec",
            "sourceColumn": "คนงานรวม",
            "summarizeBy": "none"
          },
          {
            "name": "ค่าที่ดิน",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7df655bb-6ead-47e7-8c7d-2518c6cf0318",
            "sourceColumn": "ค่าที่ดิน",
            "summarizeBy": "none"
          },
          {
            "name": "ค่าอาคาร",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae9c5efa-ab6a-4e29-94a3-25191ae39509",
            "sourceColumn": "ค่าอาคาร",
            "summarizeBy": "none"
          },
          {
            "name": "ค่าเครื่องจักร",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c91d782-18b7-4551-90ec-a230d6b49618",
            "sourceColumn": "ค่าเครื่องจักร",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "036159bb-b16f-4717-93c3-8f427680f491",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "จำพวก",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db73c842-fc13-4fa6-8064-dde9131f9ae2",
            "sourceColumn": "จำพวก",
            "summarizeBy": "none"
          },
          {
            "name": "ชาย",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a33a9b2-7ea5-4344-a7cf-63ab7956f09d",
            "sourceColumn": "ชาย",
            "summarizeBy": "none"
          },
          {
            "name": "ชื่อเจ้าของ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5f260c1-b0a1-45d4-9e0f-77949a300ac9",
            "sourceColumn": "ชื่อเจ้าของ",
            "summarizeBy": "none"
          },
          {
            "name": "ชื่อโรงงาน",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8f3a981-ac6e-4355-9a08-be230a51ec97",
            "sourceColumn": "ชื่อโรงงาน",
            "summarizeBy": "none"
          },
          {
            "name": "ซอย",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f643b0eb-6ed3-40f9-90ef-980ee05d5e43",
            "sourceColumn": "ซอย",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e3f7f2c-2902-4c44-a2b0-205ff2b6586b",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "ถนน",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afb2437f-ef84-4c64-add5-e3d7dbb4c1e3",
            "sourceColumn": "ถนน",
            "summarizeBy": "none"
          },
          {
            "name": "ประกอบกิจการ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c0a07e7-5148-44b7-887f-4ffbac1dbfec",
            "sourceColumn": "ประกอบกิจการ",
            "summarizeBy": "none"
          },
          {
            "name": "ปีที่ได้รับอนุญาต",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "679ab663-e903-426f-85c0-e6418fd9723a",
            "sourceColumn": "ปีที่ได้รับอนุญาต",
            "summarizeBy": "none"
          },
          {
            "name": "พื้นที่อาคาร(ตร.ม.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64b0ca17-6f75-4ad3-bab0-10d50d6a8ed8",
            "sourceColumn": "พื้นที่อาคาร(ตร.ม.)",
            "summarizeBy": "none"
          },
          {
            "name": "พื้นที่โรงงาน(ตร.ม.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "066aa33b-5047-4ca4-9f6e-577a0a71c42a",
            "sourceColumn": "พื้นที่โรงงาน(ตร.ม.)",
            "summarizeBy": "none"
          },
          {
            "name": "รหัสจังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab2782f8-86ff-48bd-8e01-1b8e865d119f",
            "sourceColumn": "รหัสจังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "รหัสทะเบียนโรงงาน FID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "608f1251-97e1-452d-9ad8-bce47b382be4",
            "sourceColumn": "รหัสทะเบียนโรงงาน FID",
            "summarizeBy": "none"
          },
          {
            "name": "รหัสประเภท",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74f0b441-db76-4db3-bfd7-9be81ac49c34",
            "sourceColumn": "รหัสประเภท",
            "summarizeBy": "none"
          },
          {
            "name": "รหัสไปรษณีย์",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99b4a8e8-8cf6-4ba9-ae32-bde26cd986d4",
            "sourceColumn": "รหัสไปรษณีย์",
            "summarizeBy": "none"
          },
          {
            "name": "ลำดับ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c49132d-6808-4608-872b-100c068cf9fc",
            "sourceColumn": "ลำดับ",
            "summarizeBy": "none"
          },
          {
            "name": "หญิง",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f495690-a75d-443a-8374-060f491b9fbe",
            "sourceColumn": "หญิง",
            "summarizeBy": "none"
          },
          {
            "name": "หมู่",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9306ef54-323c-4a53-8f50-e854bf7b6999",
            "sourceColumn": "หมู่",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a46e6a0e-4386-42f2-afcf-a1f0a61743b7",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          },
          {
            "name": "เงินทุนหมุนเวียน",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b8cda24-e3c2-4187-8747-accccfa59a5a",
            "sourceColumn": "เงินทุนหมุนเวียน",
            "summarizeBy": "none"
          },
          {
            "name": "เงินลงทุนรวม",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f2680e0-b04c-4b3c-a2a7-b8788e6b0117",
            "sourceColumn": "เงินลงทุนรวม",
            "summarizeBy": "none"
          },
          {
            "name": "เลขทะเบียนโรงงาน",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "070b6943-4ab2-4fc2-a35a-47f01b5d4d33",
            "sourceColumn": "เลขทะเบียนโรงงาน",
            "summarizeBy": "none"
          },
          {
            "name": "เลขที่",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2ca33d8-24d4-409f-8745-219cab720381",
            "sourceColumn": "เลขที่",
            "summarizeBy": "none"
          },
          {
            "name": "แรงม้ารวม",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbf326c2-ae9d-4143-8b4a-fee8eddf4d87",
            "sourceColumn": "แรงม้ารวม",
            "summarizeBy": "none"
          },
          {
            "name": "โทรศัพท์",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc10b0ef-32f2-4493-9241-0b45a8ca42bd",
            "sourceColumn": "โทรศัพท์",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a06788c6-c96a-4022-99a8-d8e3b187926d",
        "partitions": [
          {
            "name": "eec data file",
            "mode": "import",
            "queryGroup": "Data Source",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://data.go.th/dataset/656b9ca7-10b5-4c33-87b0-188ed5fe4078/resource/b7acb5f0-e593-4437-a159-c3e761843fa8/download/eec.csv\"),[Delimiter=\",\", Columns=31, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Trimmed Text\" = Table.TransformColumns(Source,{{\"Column1\", Text.Trim, type text}, {\"Column2\", Text.Trim, type text}, {\"Column3\", Text.Trim, type text}, {\"Column4\", Text.Trim, type text}, {\"Column5\", Text.Trim, type text}, {\"Column6\", Text.Trim, type text}, {\"Column7\", Text.Trim, type text}, {\"Column8\", Text.Trim, type text}, {\"Column9\", Text.Trim, type text}, {\"Column10\", Text.Trim, type text}, {\"Column11\", Text.Trim, type text}, {\"Column12\", Text.Trim, type text}, {\"Column13\", Text.Trim, type text}, {\"Column14\", Text.Trim, type text}, {\"Column15\", Text.Trim, type text}, {\"Column16\", Text.Trim, type text}, {\"Column17\", Text.Trim, type text}, {\"Column18\", Text.Trim, type text}, {\"Column19\", Text.Trim, type text}, {\"Column20\", Text.Trim, type text}, {\"Column21\", Text.Trim, type text}, {\"Column22\", Text.Trim, type text}, {\"Column23\", Text.Trim, type text}, {\"Column24\", Text.Trim, type text}, {\"Column25\", Text.Trim, type text}, {\"Column26\", Text.Trim, type text}, {\"Column27\", Text.Trim, type text}, {\"Column28\", Text.Trim, type text}, {\"Column29\", Text.Trim, type text}, {\"Column30\", Text.Trim, type text}, {\"Column31\", Text.Trim, type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Trimmed Text\", [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}