{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"eec data source file\",\"Sub-district Lookup\",\"Tambon A\",\"Tambon B\",\"Tambon C\",\"Tambon D\",\"Tambon E-F\",\"Tambon H-I\",\"Tambon K\",\"Tambon L\",\"Tambon M\",\"Tambon N-O\",\"Tambon P\",\"Tambon R\",\"Tambon S\",\"Tambon T\",\"Tambon U-V\",\"Tambon W\",\"Tambon Y\",\"Sub-districts (All Thailand)\",\"Missing Tambon\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.119.870.0 (23.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Sub District Queries to builld Tambon Table"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Data Source"
      }
    ],
    "relationships": [
      {
        "name": "fd13bd83-ffea-4927-b847-4f67c795d26f",
        "fromColumn": "Amphoe (District)",
        "fromTable": "Tambon H-I",
        "toColumn": "Amphoe (District)",
        "toTable": "Tambon E-F"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_672b22fe-0c56-4d42-8812-cd012a05872f",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a7669f2c-c128-405d-b678-d0199a2a076a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0280b95b-f3be-45d5-bb1a-adb38e164af7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "920e74e9-b4d7-4b28-9c0c-92a2e0216024",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "80c1e8a6-6cec-4f04-b912-308a24d9c509",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c96c8627-2ea0-43e4-b160-f98ca426ce8f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "93728779-2160-4e2f-97be-4fe32e2a042d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba7a0ead-0ff2-45a2-b7e6-88eb4761b472",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "08d041e8-bed7-4ae1-9c0c-8ceee9b9b9f6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8c9ceffc-5024-4d44-8ebd-ec56005b8a9b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6d0d783d-4676-44fc-81e5-7a7189c82c71",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dbbee82a-0ecc-4752-acc7-43348c2c2c1d",
                "ordinal": 3
              }
            ],
            "lineageTag": "001e648d-6bba-402e-a4a9-f984769070c3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "7abf2252-8e38-4d6e-83ad-2e23b4b09036",
        "partitions": [
          {
            "name": "DateTableTemplate_672b22fe-0c56-4d42-8812-cd012a05872f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Missing Tambon",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b63a555e-fac8-4ce8-ba3a-700ba17a66d5",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e1db6df-5326-4084-86a9-c3b7a93e15df",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d17cf85-6f35-4be8-9cac-06bb59bb8d8e",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "394c053d-b3c7-4b7b-8067-502f4b5f5473",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf1b775d-2736-410b-b11f-e898c3183439",
            "sourceColumn": "Tambon Code",
            "summarizeBy": "count"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1eab1c01-5cd8-49c6-aa1f-f4d870d829e0",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9313ed7-94f6-47b1-8a0b-a6ee88d3f648",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc511677-959b-446c-b9d4-351ff075665f",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a31d9be7-053c-44f0-aaa4-61aabff4d386",
        "partitions": [
          {
            "name": "Missing Tambon",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"rVCxCsJADP0V6ezQ6uRqcRJEcHAoHU4RW9Q7aHVXEar9AbFOIqIogopC+jf5FHM5XZxdQnh5yXsvnmc5Fdu2raJVVYV2KKlByDBfIlwRjghPhA2BrTAS3UDw+ISwR3hxfSCkVAl3AyU7kyhkCmEHfQfAcAmsiXhs+UUj6BBQD4QqUJGxkn29lU8R5nxygXAnXYQ1ryf/N1DSJ0mXDAw/8nDmzAnLH0yv/yKI1RSDLytjTWJtEW4IM8NyA3KnerIfC8W0lZ7qRCn/MOHexHn8mikT0DBmxIi3L5zeuDEv2f3xB/4b\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Tambon Code\" = _t, Tambon = _t, ตำบล = _t, #\"Amphoe (District)\" = _t, อำเภอ = _t, #\"Changwat (Province)\" = _t, จังหวัด = _t, Region = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Tambon Code\", Int64.Type}, {\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sub-district Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sub-district",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1224a5d5-0bb4-456c-850f-96bf174688f4",
            "sourceColumn": "sub-district",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district (EN)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "975792c6-81a6-4310-958c-9390fc9da893",
            "sourceColumn": "sub-district (EN)",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district (TH)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ee8dbdb-1730-4195-9762-202364069d51",
            "sourceColumn": "sub-district (TH)",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0fcbefc4-24f2-4db2-a36c-3e8b4c8c3544",
            "sourceColumn": "sub-district code",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b14da4be-87fa-4129-b6f1-c0e419a0a686",
        "partitions": [
          {
            "name": "Sub-district Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Sub-districts (All Thailand)\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Region] = \"East\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Amphoe (District)\", \"อำเภอ\", \"Changwat (Province)\", \"จังหวัด\", \"Region\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\", {\"ตำบล\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"Tambon\", \"Sub-district (EN)\"}, {\"ตำบล\", \"Sub-district (TH)\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Tambon Code\", \"Sub-district (TH)\", \"Sub-district (EN)\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Tambon Code\", \"sub-district code\"}, {\"Sub-district (TH)\", \"sub-district (TH)\"}, {\"Sub-district (EN)\", \"sub-district (EN)\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"sub-district\", each [#\"sub-district (TH)\"] & \" / \" & [#\"sub-district (EN)\"])",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sub-districts (All Thailand)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3a21596-4e50-48b0-92de-292a26ac7e61",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a37fe98-769b-4af8-8320-cd7532e2e515",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ca5b45a-232d-4636-b2a8-de457f1220f3",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e79d2027-efc3-443e-bf9b-559c3226f197",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e861292-9aef-4550-8df3-ed2ccbcf4c26",
            "sourceColumn": "Tambon Code",
            "summarizeBy": "count"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "390530e9-4f3f-4e46-a004-f2e6ddf3bf4c",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b83c9edf-54ad-4aaf-b647-8b2333eed383",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27cf5b14-fb1f-48e7-8707-1b33fe5c3141",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9da72cca-3452-41eb-b8f6-7c3669685194",
        "partitions": [
          {
            "name": "Sub-districts (All Thailand)",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({#\"Tambon A\", #\"Tambon B\", #\"Tambon C\", #\"Tambon D\", #\"Tambon E-F\", #\"Tambon H-I\", #\"Tambon K\", #\"Tambon L\", #\"Tambon M\", #\"Tambon N-O\", #\"Tambon P\", #\"Tambon R\", #\"Tambon S\", #\"Tambon T\", #\"Tambon U-V\", #\"Tambon W\", #\"Tambon Y\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(Source, \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"Tambon Code\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Tambon Code\", \"Tambon\", \"ตำบล\", \"Amphoe (District)\", \"อำเภอ\", \"Changwat (Province)\", \"จังหวัด\", \"Region\"}),",
                "    #\"Appended Query\" = Table.Combine({#\"Reordered Columns\", #\"Missing Tambon\"})",
                "in",
                "    #\"Appended Query\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon A",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e6df34e-e203-4cde-84e6-80afa78810eb",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0051322-11b3-4079-b4d9-5c5915647921",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43075319-7c76-4ea3-8a29-194ee0a2fb11",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25d6e932-9e9e-4b1b-bc7c-b62430cc9097",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8bb527e-6049-40e4-8bb4-f911bb1aea08",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "893e1d27-c6cb-4a7d-b297-64cc70d35e1d",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e3f7c83-b029-431d-ac5f-b7bcc4c8c52f",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ce91a875-a463-4971-8bbd-edd1d8602618",
        "partitions": [
          {
            "name": "Tambon A",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(A)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Data0,{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon B",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "833671fc-cb9c-4cc2-88a3-7b234f4e1a8d",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a769e335-1ee1-4ded-956f-0a6a5cbfd6e9",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be921b6d-2225-4aaf-846b-2c5ec9c0ee4d",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b5c720d-6890-4d28-a832-23b7b90bd235",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f70752b-5caa-44d8-91b3-050df3c61a7a",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cb56779-bac8-488a-bc13-b77d60eecbfe",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae28481c-ad2a-40a7-aee3-325f6a9cae3a",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a51a5712-f814-4206-b8ae-7e828478cc58",
        "partitions": [
          {
            "name": "Tambon B",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(B)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Data0,{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon C",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "495b572d-ae32-4d75-b44e-36cb118e8dfa",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6044c1c2-d5a7-4a71-92e8-08cbe6b6d181",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01d0b9b9-fba9-480a-9248-ab15d5649028",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7027277-7f70-419f-89aa-37534d98b82a",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "747b4cac-b8c8-4fa7-9323-4778d4e08cd1",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f724ca5f-566d-4c80-942c-b38733781b27",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf396edb-d615-41f6-a9b5-e7d25cf786ac",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2048aabe-e4de-4c72-a40d-86ec5cc4b924",
        "partitions": [
          {
            "name": "Tambon C",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(C)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon D",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c445f44a-ee87-44e0-8c50-91e41ee4748b",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "639ab0d7-e3f3-4bce-9a06-4a184eda31e1",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed889d80-5b99-4c24-bf3e-0fce36a9a53e",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03c538d6-49ff-48af-9a23-da1df30e0725",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "428bd24d-cbda-401a-921e-5a7ced407b31",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09dae5f5-5343-4912-a3aa-937d6ba7bd1c",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36f61664-720b-4fb8-bbf3-9d2d6414e698",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "962a07b8-6cc3-4a96-98fa-73f39e9dcb4e",
        "partitions": [
          {
            "name": "Tambon D",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(D)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon E-F",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6e02d72-f976-492e-9d25-952c80e49ac9",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c6def5b-e5df-4f84-856e-fff11c3e4b7b",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fe1432f-8443-4152-a7de-58e7f5c5ea42",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "482633cf-3509-45fe-82b8-a5136e165f6e",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e28cf7bb-2061-4943-88b0-d53285e59817",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8a856cf-dafc-4293-9849-dbfc8571b15a",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcbb49d5-e868-402c-b7cf-f708812e093a",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f82a4e22-0023-43d2-b508-7dd52a70df1d",
        "partitions": [
          {
            "name": "Tambon E-F",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(E-F)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon H-I",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e27b067-0bd9-43f0-8aa1-33f9fdeec27a",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0587323c-1334-4277-9757-229cbf7e035e",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9913a50a-5dc4-4a73-88ef-d4fde0385f35",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d8b6125-c592-4149-b69c-312284f7c5a0",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e5b1bbd-ccb7-452a-8a35-68d3aed32c11",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12cb2d90-5991-4b1e-ab79-3d70ce688d85",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a93f5e8-b5fa-4101-9fb8-98edf694d149",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "95bc8f86-da12-43f9-91e4-ce121826780d",
        "partitions": [
          {
            "name": "Tambon H-I",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(H-I)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon K",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1d16a81-fa4c-47a0-9760-d1669fea3e07",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "038c632d-0f78-407a-bf9d-2cffb7b310d1",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33e75576-9641-483e-8eb0-e70ad43db3d6",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2649d4b3-22aa-4c9e-b2ce-6c5be08cac98",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f72df85-a635-4018-9a2e-51f333292211",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "626a8f2e-8e81-4f82-8596-d9864dd36b6c",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b74e5f96-8399-4f1b-a867-61a834502085",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7f36734a-bad2-46f5-9af5-aa1c48b09432",
        "partitions": [
          {
            "name": "Tambon K",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(K)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon L",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fd6e8eb-d7e5-467c-85ab-f5de30cabdb5",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10292abd-32f0-4278-ac95-68e21636e5d2",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d0f7a62-dace-45e7-bdfb-4661199cd757",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd3f3fb4-f9a5-488f-ab95-4c80fecb8153",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "564f73cc-7e8b-4d38-a272-2ea4235fcba6",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d413ee0-3cb6-4e7e-a85b-4308f07d9f96",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d640e28-d59f-4938-a7ab-15a64f3680e6",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2e918292-89c3-4d2a-b10a-66cf526d7c22",
        "partitions": [
          {
            "name": "Tambon L",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(L)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon M",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11fa2ba2-a3ad-481f-8f5a-b85e092c4b74",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e6c211b-0d8d-432b-a33b-0ff0b2fdf9f2",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62706cd0-6eb9-4a70-9717-111674b00245",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f22149c1-8e27-413c-b1d3-5ddbd787a71c",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e3eb2c4-a8ea-4a25-b6d4-4ac01ed81cc2",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "427e4801-921b-4a0a-a246-fee07dd90d87",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a20702f6-3706-4a73-919d-49e6145b91d3",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8bf961b0-16b5-46fc-87c8-4572490117ae",
        "partitions": [
          {
            "name": "Tambon M",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(M)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Data0,{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon N-O",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fa1000f-0070-4087-8c1f-7fdb30ecf14b",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cc76e5b-021e-4605-8ab0-5f64ba95537c",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a8a67a7-7633-4efc-9074-b686bbaffcd8",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a369f01-8b82-4f27-852c-be661f501128",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd547974-94b8-47d5-8c7c-f541d7150b84",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4da30c6-bef2-4e65-8215-c01a4184f68b",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84398102-8172-44db-91e6-c9120d26eba5",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4750d3bc-0816-4487-bcca-33848db99489",
        "partitions": [
          {
            "name": "Tambon N-O",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(N-O)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}, {\"Changwat\", \"Changwat (Province)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon P",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d74a8323-e28c-4d4a-8fa9-9259f8e02891",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39309d9b-2ac5-4ae4-8b17-ac18c2a8a4bb",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "166afd9a-2864-4cd1-a447-99dd4cc1cfde",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "882bb8c6-94e6-450c-8e4b-9fbf88262c78",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "009959a2-d714-44e9-8ec2-6af72e929d49",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f0a4602-7a5d-47eb-b420-00ef0350df72",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "234e98cc-8691-422a-92e0-dc9bca2e6f47",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "533d2d5a-e97d-4696-a6ad-c6b02efe495a",
        "partitions": [
          {
            "name": "Tambon P",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(P)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon R",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1038f195-77e1-4fac-ad52-3f03db5ea006",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f3f0a73-8857-478f-ac98-d75a7cdf3737",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d50c0eb-3fd3-4269-82e5-5179e7e54b7a",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81b523dc-8b92-4865-92f1-b11d05273ae2",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e907fc23-3845-4308-95b1-8311427d43f2",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b87b9cb2-049d-44dc-96d1-b9aa7fb7b7ef",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10debad1-35b5-4e4b-84dd-0778e0599d61",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7affdf39-ea83-4ba3-a0f1-4208c15c7434",
        "partitions": [
          {
            "name": "Tambon R",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(R)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns1\" = Table.RenameColumns(Data0,{{\"District (amphoe)\", \"Amphoe (District)\"}, {\"Province (changwat)\", \"Changwat (Province)\"}, {\"Sub-district (tambon)\", \"Tambon\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon S",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3dea72b-0c51-4516-92c4-6ffa3cb72be4",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6056d17a-05d1-49d3-ad54-abfb539cb4b0",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7fd0375-8a0a-4c7a-89bd-142c33873a52",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9d6a043-b2cd-46a1-99d5-790b80a9c0ba",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09931f22-959f-4207-90aa-3afb7ea506ef",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0b04ab2-b1ee-4355-b813-5a32d37ba945",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "757d4ec9-30c2-4991-950a-92c112bf0cc0",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "54fba3c3-fa90-4c13-bea7-e637e172f456",
        "partitions": [
          {
            "name": "Tambon S",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(S)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon T",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b487ecb4-3d56-4244-9659-b5481c72da1d",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb8383ad-3f16-4860-85dd-84d92eb11aee",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64297db3-fbef-4b67-816a-cfe5ec787e5f",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f46d4250-165c-41c8-b1c3-ce56c2dc263c",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33406283-b7c0-45b4-9c1b-af2a2dd366ba",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2daa920f-c650-46ea-861b-7a6c7d5aba87",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f712ba2-76a5-4f9c-9778-c8154b0a6a60",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d2429ded-1590-4773-a294-49579d08da99",
        "partitions": [
          {
            "name": "Tambon T",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(T)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon U-V",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a7eed3f-537a-4dda-8971-7189418a64b9",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3cc14c3-946a-40b9-9692-206b817f78aa",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf4be87a-389c-43cf-ae80-bb7d15a9e3a6",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d46ed99a-2a79-4abc-a47e-0e144f0f894a",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82da0290-16ac-4c0c-88f1-6b41876c8090",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc18e1d1-c73c-45a8-854d-e6878413c173",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d19519d9-c782-4e90-b69c-84395403d6e4",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "63ad19dc-14f2-4853-aa7c-6b4dd8317f2f",
        "partitions": [
          {
            "name": "Tambon U-V",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(U-V)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon W",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b38b85a9-7d61-4e34-8d64-65af65d2b735",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4a85e81-ba7d-467b-b55d-a01457cd2ac8",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53fe51d6-0d36-4dee-83a9-512a2f685ae4",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b68cd513-717b-4d0f-8738-698a90d73ed2",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c55bdbf5-9c35-4975-b111-2f0703884a36",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b1d0241-d44b-4f40-b788-7bc3c009dee9",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "339bf213-77ef-43a8-a51f-4f407d716935",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5c0fd158-540e-4302-a899-82b9cc1f6511",
        "partitions": [
          {
            "name": "Tambon W",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(W)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tambon Y",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amphoe (District)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "454684d0-d302-43f7-b2bc-88572762c52a",
            "sourceColumn": "Amphoe (District)",
            "summarizeBy": "none"
          },
          {
            "name": "Changwat (Province)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfbaa20d-6623-4c18-8280-e167792455bd",
            "sourceColumn": "Changwat (Province)",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "648f6d68-fbfc-4561-998f-359249485b8e",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tambon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78392629-2c7c-4710-95f1-5f9b83b3fa57",
            "sourceColumn": "Tambon",
            "summarizeBy": "none"
          },
          {
            "name": "จังหวัด",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c593b97a-105b-4f03-a1e5-a4d321c73315",
            "sourceColumn": "จังหวัด",
            "summarizeBy": "none"
          },
          {
            "name": "ตำบล",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91c21e2e-1a87-457b-a351-52a19074ecf4",
            "sourceColumn": "ตำบล",
            "summarizeBy": "none"
          },
          {
            "name": "อำเภอ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90d6f4d1-ae10-4d97-bdb8-8b638a7059f2",
            "sourceColumn": "อำเภอ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8985ff51-0227-404d-9a95-7b6adde09543",
        "partitions": [
          {
            "name": "Tambon Y",
            "mode": "import",
            "queryGroup": "Sub District Queries to builld Tambon Table",
            "source": {
              "expression": [
                "let",
                "    Source = Web.Page(Web.Contents(\"https://en.wikipedia.org/wiki/List_of_tambon_in_Thailand_(Y)\")),",
                "    Data0 = Source{0}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(Data0,{{\"Amphoe\", \"Amphoe (District)\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Tambon\", type text}, {\"ตำบล\", type text}, {\"Amphoe (District)\", type text}, {\"อำเภอ\", type text}, {\"Changwat (Province)\", type text}, {\"จังหวัด\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "eec data source file",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Building area (sq.m.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cbbf0753-a7d6-404f-b843-e5d9d5da95e9",
            "sourceColumn": "Building area (sq.m.)",
            "summarizeBy": "sum"
          },
          {
            "name": "FID factory registration code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6657a83f-8539-47f6-9db7-b8623ba080a3",
            "sourceColumn": "FID factory registration code",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41151d6c-3cad-40e9-825c-23543d785026",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          },
          {
            "name": "TSIC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58300ad4-f7ae-400b-8cab-0288f3c48118",
            "sourceColumn": "TSIC",
            "summarizeBy": "none"
          },
          {
            "name": "building value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f80fd26a-2fc3-4e55-862c-07655a34424e",
            "sourceColumn": "building value",
            "summarizeBy": "sum"
          },
          {
            "name": "business (EN)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf5f86dc-0b90-46d2-8475-dfab7af6c04e",
            "sourceColumn": "business (EN)",
            "summarizeBy": "none"
          },
          {
            "name": "business (TH)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c0a07e7-5148-44b7-887f-4ffbac1dbfec",
            "sourceColumn": "business (TH)",
            "summarizeBy": "none"
          },
          {
            "name": "district",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a46e6a0e-4386-42f2-afcf-a1f0a61743b7",
            "sourceColumn": "district",
            "summarizeBy": "none"
          },
          {
            "name": "factory area (sq.m.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27f4f73b-ecb3-4e18-83fc-62db5af50002",
            "sourceColumn": "factory area (sq.m.)",
            "summarizeBy": "sum"
          },
          {
            "name": "factory name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8f3a981-ac6e-4355-9a08-be230a51ec97",
            "sourceColumn": "factory name",
            "summarizeBy": "none"
          },
          {
            "name": "factory registration number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "070b6943-4ab2-4fc2-a35a-47f01b5d4d33",
            "sourceColumn": "factory registration number",
            "summarizeBy": "none"
          },
          {
            "name": "female",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec8d8178-2f4a-45e4-9186-95f9b55d4c5e",
            "sourceColumn": "female",
            "summarizeBy": "sum"
          },
          {
            "name": "group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db73c842-fc13-4fa6-8064-dde9131f9ae2",
            "sourceColumn": "group",
            "summarizeBy": "none"
          },
          {
            "name": "land value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "7d6ce1a8-e0d2-417b-be79-8f38a9315525",
            "sourceColumn": "land value",
            "summarizeBy": "sum"
          },
          {
            "name": "licensed year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "679ab663-e903-426f-85c0-e6418fd9723a",
            "sourceColumn": "licensed year",
            "summarizeBy": "none"
          },
          {
            "name": "machine cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "34c70f58-6830-43a8-a44e-9bcfc51fb57f",
            "sourceColumn": "machine cost",
            "summarizeBy": "sum"
          },
          {
            "name": "male",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aaa5af90-c6f4-4b7a-b785-0fcdde02bd6c",
            "sourceColumn": "male",
            "summarizeBy": "sum"
          },
          {
            "name": "moo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9306ef54-323c-4a53-8f50-e854bf7b6999",
            "sourceColumn": "moo",
            "summarizeBy": "none"
          },
          {
            "name": "number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2ca33d8-24d4-409f-8745-219cab720381",
            "sourceColumn": "number",
            "summarizeBy": "none"
          },
          {
            "name": "owner name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5f260c1-b0a1-45d4-9e0f-77949a300ac9",
            "sourceColumn": "owner name",
            "summarizeBy": "none"
          },
          {
            "name": "post code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c1da608-0171-4dc0-87c6-a51566323ca3",
            "sourceColumn": "post code",
            "summarizeBy": "none"
          },
          {
            "name": "province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17b4047c-8efb-4c79-a49d-e146b77ada05",
            "sourceColumn": "province",
            "summarizeBy": "none"
          },
          {
            "name": "province code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab2782f8-86ff-48bd-8e01-1b8e865d119f",
            "sourceColumn": "province code",
            "summarizeBy": "none"
          },
          {
            "name": "road",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afb2437f-ef84-4c64-add5-e3d7dbb4c1e3",
            "sourceColumn": "road",
            "summarizeBy": "none"
          },
          {
            "name": "soi",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f643b0eb-6ed3-40f9-90ef-980ee05d5e43",
            "sourceColumn": "soi",
            "summarizeBy": "none"
          },
          {
            "name": "sub-district",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e3f7f2c-2902-4c44-a2b0-205ff2b6586b",
            "sourceColumn": "sub-district",
            "summarizeBy": "none"
          },
          {
            "name": "telephone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38704ae6-76ec-44c3-9d9d-43c56c229f2f",
            "sourceColumn": "telephone",
            "summarizeBy": "none"
          },
          {
            "name": "total horsepower",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f8e59842-2883-427d-894a-6f7c54b1c274",
            "sourceColumn": "total horsepower",
            "summarizeBy": "sum"
          },
          {
            "name": "total investment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "d2f6ad11-18e3-407b-8d66-e39eb98dde55",
            "sourceColumn": "total investment",
            "summarizeBy": "sum"
          },
          {
            "name": "total workers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c4f0b4bf-70ae-4d4e-962f-49188ee4dd23",
            "sourceColumn": "total workers",
            "summarizeBy": "sum"
          },
          {
            "name": "type code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74f0b441-db76-4db3-bfd7-9be81ac49c34",
            "sourceColumn": "type code",
            "summarizeBy": "none"
          },
          {
            "name": "working capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "e4cd8ec3-0966-44b7-8937-552ca69eb0f9",
            "sourceColumn": "working capital",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a06788c6-c96a-4022-99a8-d8e3b187926d",
        "partitions": [
          {
            "name": "eec data source file",
            "mode": "import",
            "queryGroup": "Data Source",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://data.go.th/dataset/656b9ca7-10b5-4c33-87b0-188ed5fe4078/resource/b7acb5f0-e593-4437-a159-c3e761843fa8/download/eec.csv\"),[Delimiter=\",\", Columns=31, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"รหัสทะเบียนโรงงาน FID\", Int64.Type}}),    ",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"FID factory registration code\", each Number.ToText([รหัสทะเบียนโรงงาน FID],\"0\")),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Custom\",{\"ลำดับ\", \"เลขทะเบียนโรงงาน\", \"รหัสทะเบียนโรงงาน FID\", \"FID factory registration code\", \"TSIC\", \"รหัสประเภท\", \"จำพวก\", \"ปีที่ได้รับอนุญาต\", \"ชื่อโรงงาน\", \"ชื่อเจ้าของ\", \"ประกอบกิจการ\", \"เลขที่\", \"หมู่\", \"ซอย\", \"ถนน\", \"ตำบล\", \"อำเภอ\", \"รหัสจังหวัด\", \" จังหวัด \", \" รหัสไปรษณีย์ \", \" โทรศัพท์ \", \" ค่าอาคาร \", \" ค่าที่ดิน \", \" ค่าเครื่องจักร \", \" เงินทุนหมุนเวียน \", \" เงินลงทุนรวม \", \" ชาย \", \" หญิง \", \" คนงานรวม \", \" แรงม้ารวม \", \" พื้นที่โรงงาน(ตร.ม.) \", \" พื้นที่อาคาร(ตร.ม.) \"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"รหัสทะเบียนโรงงาน FID\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"ลำดับ\", \"Index\"}, {\"เลขทะเบียนโรงงาน\", \"factory registration number\"}, {\"รหัสประเภท\", \"type code\"}, {\"จำพวก\", \"group\"}, {\"ปีที่ได้รับอนุญาต\", \"licensed year\"}, {\"ชื่อโรงงาน\", \"factory name\"}, {\"ชื่อเจ้าของ\", \"owner name\"}, {\"ประกอบกิจการ\", \"business\"}, {\"เลขที่\", \"number\"}, {\"หมู่\", \"moo\"}, {\"ซอย\", \"soi\"}, {\"ถนน\", \"road\"}, {\"ตำบล\", \"sub-district\"}, {\"อำเภอ\", \"district\"}, {\"รหัสจังหวัด\", \"province code\"}, {\" จังหวัด \", \"province\"}, {\" รหัสไปรษณีย์ \", \"post code\"}, {\" โทรศัพท์ \", \"telephone\"}, {\" ค่าอาคาร \", \"building value\"}, {\" ค่าที่ดิน \", \"land value\"}, {\" ค่าเครื่องจักร \", \"machine cost\"}, {\" เงินลงทุนรวม \", \"total investment\"}, {\" เงินทุนหมุนเวียน \", \"working capital\"}, {\" ชาย \", \"male\"}, {\" หญิง \", \"female\"}, {\" คนงานรวม \", \"total workers\"}, {\" แรงม้ารวม \", \"total horsepower\"}, {\" พื้นที่โรงงาน(ตร.ม.) \", \"factory area (sq.m.)\"}, {\" พื้นที่อาคาร(ตร.ม.) \", \"Building area (sq.m.)\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns\", \"business\", \"business - Copy\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"business - Copy\", \"business (EN)\"}, {\"business\", \"business (TH)\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"Index\", \"factory registration number\", \"FID factory registration code\", \"TSIC\", \"type code\", \"group\", \"licensed year\", \"factory name\", \"owner name\", \"business (TH)\", \"business (EN)\", \"number\", \"moo\", \"soi\", \"road\", \"sub-district\", \"district\", \"province code\", \"province\", \"post code\", \"telephone\", \"building value\", \"land value\", \"machine cost\", \"working capital\", \"total investment\", \"male\", \"female\", \"total workers\", \"total horsepower\", \"factory area (sq.m.)\", \"Building area (sq.m.)\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Reordered Columns1\",\"ขุดดิน\",\"digging\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"ขุดทราย\",\"digging sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"ร่อน คัดขนาดทราย\",\" soil, sifting, sorting sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"ร่อน คัดขนาด ทราย\",\"sifting, grading, sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"บดหรือป่นเครื่องเทศ ผลิตเครื่องแกง และผลิตภัณฑ์อาหารสำเร็จรูปจากเนื้อสัตว์ เช่น น้ำพริกปลาสลิด น้ำพริกปลาทู#(tab)\",\"ground or ground spices production of curry paste and ready-made food products from meat such as gourami fish chili paste, mackerel chili paste\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"ผลิตน้ำมันพืชจากงา และพืชอื่น ๆ\",\"Producing vegetable oil from sesame and other plants\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"ผลิตแป้งมันสำปะหลัง\",\"Production of cassava starch\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"ทำโรงงานเม็ดสาคูเพื่อขายให้กับชุมชนเพื่อนำไปผลิตเป็นอาหารหรือขนมขายให้กับนักท่องเที่ยว\",\"Build a sago seed factory to sell to the community in order to produce food or snacks for sale to tourists.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"ผลิตอาหารสัตว์\",\"feed production\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"ผลิตน้ำแข็งก้อนเล็ก\",\"produce small ice cubes\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"ผลิตถุงมือทุกชนิด\",\"produce all kinds of gloves\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"ทำน้ำแข็งก้อนเล็ก\",\"make small ice cubes\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"ทำน้ำแข็งก้อนเล็ก\",\"make small ice cubes\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"คัดแยกวัสดุที่ไม่ใช้แล้วที่ไม่เป็นของเสียอันตราย\",\"Separate unused materials that are not hazardous waste.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"แปรรูปไม้ ทำวงกบประตู หน้าต่าง และทำเครื่องเรือน เช่น เฟอร์นิเจอร์จากไม้\",\"Processing wood, making door frames, windows, and making furniture such as furniture from wood.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Replaced Value14\",\"ทำวงกบ ประตู หน้าต่างจากไม้แปรรูป\",\"Make door frames, windows from sawn timber.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",\"ผลิตเชื้อเพลิงแข็งอัดเม็ด (wood pellet)\",\"Production of solid fuel pellets (wood pellets)\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value17\" = Table.ReplaceValue(#\"Replaced Value16\",\"ผลิตชิ้นไม้สับจากไม้ที่ปลูกขึ้นโดยเฉพาะ 13 ชนิด ตามมติคณะรัฐมนตรีเพื่อจำหน่าย\",\"Produce wood chips from 13 types of specially planted wood according to the cabinet resolution for sale.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value18\" = Table.ReplaceValue(#\"Replaced Value17\",\"ผลิตก้อนชีวมวลสำหรับใช้ในฟาร์ม และเชื้อเพลิงอัดก้อน/แท่ง\",\"Production of biomass briquettes for use on farms and fuel briquettes/sticks\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value19\" = Table.ReplaceValue(#\"Replaced Value18\",\"ผลิตปุ๋ยอินทรีย์\",\"organic fertilizer production\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value20\" = Table.ReplaceValue(#\"Replaced Value19\",\"แปรรูปไม้เพื่อประดิษฐกรรม ไส ซอย ทำวงกบ ประตูหน้าต่าง และเครื่องเรือนเครื่องใช้จากไม้\",\"Processing wood for invention, planing, alley, making frames, doors, windows and wooden furniture\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value21\" = Table.ReplaceValue(#\"Replaced Value20\",\"อบไม้และอัดน้ำยาไม้\",\"Wood drying and compressing wood solution\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value22\" = Table.ReplaceValue(#\"Replaced Value21\",\"หั่น ตัด บด รีดยาง\",\"Cut, cut, grind, roll rubber\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value23\" = Table.ReplaceValue(#\"Replaced Value22\",\"ผลิตคอนกรีตผสมเสร็จ\",\"Production of ready-mixed concrete\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value24\" = Table.ReplaceValue(#\"Replaced Value23\",\"ทำแป้งมันสำปะหลัง\",\"make cassava flour\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value25\" = Table.ReplaceValue(#\"Replaced Value24\",\"ทำแป้งมัน ได้เดือนละ 30 ตัน\",\"can produce 30 tons of tapioca starch per month\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value26\" = Table.ReplaceValue(#\"Replaced Value25\",\"ทำแผ่นรองสินค้าจากไม้ (พาเลท) ลังไม้\",\"Making product pads from wood (pallets), wooden crates\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value27\" = Table.ReplaceValue(#\"Replaced Value26\",\"ทำน้ำตาลก้อน\",\"make sugar cubes\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value28\" = Table.ReplaceValue(#\"Replaced Value27\",\"ผลิตน้ำแข็งหลอด\",\"tube ice production\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value29\" = Table.ReplaceValue(#\"Replaced Value28\",\"ผลิตไม้พาเลท\",\"produce wooden pallets\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value30\" = Table.ReplaceValue(#\"Replaced Value29\",\"ทำแผ่นรองรับสินค้าจากไม้ ทำลังไม้และอบไม้\",\"Make a sheet to support the product from wood. Making wooden crates and drying wood\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value31\" = Table.ReplaceValue(#\"Replaced Value30\",\"ผลิตเม็ดพลาสติก\",\"plastic pellets\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value32\" = Table.ReplaceValue(#\"Replaced Value31\",\"plastic pelletsและผลิตภัณฑ์พลาสติก เช่น จาน บรรจุภัณฑ์ ฯลฯ\",\"plastic pellets and plastic products such as plates, containers, etc.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value33\" = Table.ReplaceValue(#\"Replaced Value32\",\"digging ล้างทราย\",\"digging wash sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value34\" = Table.ReplaceValue(#\"Replaced Value33\",\"plastic pelletsเกรดบี และบดย่อยพลาสติก\",\"plastic pellets Grade B and crushing plastic\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value35\" = Table.ReplaceValue(#\"Replaced Value34\",\"ทอผ้า\",\"weaving\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value36\" = Table.ReplaceValue(#\"Replaced Value35\",\"ผลิตเฟอร์นิเจอร์\",\"furniture production\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value37\" = Table.ReplaceValue(#\"Replaced Value36\",\"digging ร่อน และคัดกรวดทราย\",\"digging, sifting and sorting gravel\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value38\" = Table.ReplaceValue(#\"Replaced Value37\",\"diggingหรือทราย\",\"digging soil or sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value39\" = Table.ReplaceValue(#\"Replaced Value38\",\"สกรู, น๊อต, สลักเกลียว, แป้นเกลียว, ชิ้นส่วนยานยนต์ และเครื่องมือแพทย์\",\"Screws, Nuts, Bolts, Nuts, Automotive Parts and medical equipment\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value40\" = Table.ReplaceValue(#\"Replaced Value39\",\"ทำยางพาราแผ่น\",\"making rubber sheets\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value41\" = Table.ReplaceValue(#\"Replaced Value40\",\"ผลิตน้ำประปา\",\"tap water production\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value42\" = Table.ReplaceValue(#\"Replaced Value41\",\"ทำลัง ภาชนะรองรับสินค้าและเครื่องเรือนจากไม้\",\"Making crates, containers and furniture from wood\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value43\" = Table.ReplaceValue(#\"Replaced Value42\",\"ทำเครื่องเรือนหรือเครื่องตบแต่งภายในอาคารจากไม้ยางพาราแปรรูป รวมถึงชิ้นส่วนของผลิตภัณฑ์ดังกล่าว\",\"make furniture or decoration in the building from processed rubber wood including parts of such products\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value44\" = Table.ReplaceValue(#\"Replaced Value43\",\"ทำเครื่องเรือนจากไม้ยางพารา\",\"Making furniture from rubber wood\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value45\" = Table.ReplaceValue(#\"Replaced Value44\",\"tap water productionจากน้ำทะเล\",\"tap water production from sea water\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value46\" = Table.ReplaceValue(#\"Replaced Value45\",\"ผลิตชิ้นส่วนละอุปกรณ์เฟอร์นิเจอร์จากไม้\",\"Production of wooden furniture parts and accessories\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value47\" = Table.ReplaceValue(#\"Replaced Value46\",\"ผลิตผลิตภัณฑ์จากโลหะทองเหลืองสำหรับใช้ในการต่อท่อและประกอบเครื่องสุขภัณฑ์\",\"Manufacture products from brass metal for use in pipe connections and assembly of sanitary ware.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value48\" = Table.ReplaceValue(#\"Replaced Value47\",\"ผลิตผลิตภัณฑ์จากโลหะทองเหลือง สำหรับใช้ในการต่อท่อและประกอบเครื่องสุขภัณฑ์\",\"Production of brass products For use in pipe connections and assembly of sanitary ware.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value49\" = Table.ReplaceValue(#\"Replaced Value48\",\"ผลิตและจำหน่ายเฟอร์นิเจอร์\",\"Manufacture and sale of furniture\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value50\" = Table.ReplaceValue(#\"Replaced Value49\",\"ฆ่าและชำแหละชิ้นส่วนสุกร\",\"Slaughter and butcher pigs.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value51\" = Table.ReplaceValue(#\"Replaced Value50\",\"ขุด ตักดิน\",\"dig, shovel\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value52\" = Table.ReplaceValue(#\"Replaced Value51\",\"ฆ่าสัตว์ (ไก่)\",\"Killing animals (chickens)\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value53\" = Table.ReplaceValue(#\"Replaced Value52\",\"ฆ่า ชำแหละไก่ และทำไก๋แช่แข็ง\",\"Killing, butchering chickens and making frozen chicken\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value54\" = Table.ReplaceValue(#\"Replaced Value53\",\"ซํก อบ รีด\",\"Wash, dry, iron\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value55\" = Table.ReplaceValue(#\"Replaced Value54\",\"ชุดดิน ร่อนคัดทราย\",\"Soil set, sifting sand\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value56\" = Table.ReplaceValue(#\"Replaced Value55\",\"ทำเม็ดสาคู\",\"make sago seed\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value57\" = Table.ReplaceValue(#\"Replaced Value56\",\"ทำไม้อัด\",\"make plywood\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value58\" = Table.ReplaceValue(#\"Replaced Value57\",\"ผสมและบรรจุสารปราบศัตรูพืชและปุ๋ยเคมี\",\"Mix and pack pesticides and chemical fertilizers.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value59\" = Table.ReplaceValue(#\"Replaced Value58\",\"ผลิตสีทาหรือพ่นในโรงงานอุตสาหกรรมก่อสร้าง\",\"Manufacture of paint or spray paint in the construction industry\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value60\" = Table.ReplaceValue(#\"Replaced Value59\",\"ผลิตยางแผ่น (Master Batch) และตัดแผ่นพื้นรองเท้า\",\"Production of rubber sheets (Master Batch) and cut the shoe soles.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value61\" = Table.ReplaceValue(#\"Replaced Value60\",\"ฉีดพลาสติกเป็นชิ้นส่วนอะไหล่ของกระเป๋าเดินทางและผลิตกระเป๋าเดินทาง\",\"Plastic injection for luggage spare parts and luggage production\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value62\" = Table.ReplaceValue(#\"Replaced Value61\",\"ผลิตชิ้นส่วนเรื่องใช้ไฟฟ้า และชิ้นส่วนรถยนต์พลาสติก\",\"Production of electrical parts and plastic auto parts\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value63\" = Table.ReplaceValue(#\"Replaced Value62\",\"ผลิตภัณฑ์ถุงพลาสติก\",\"plastic bag products\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value64\" = Table.ReplaceValue(#\"Replaced Value63\",\"ทำภาชนะบรรจุ เช่น ถุงหรือกระสอบ\",\"Make containers such as bags or sacks.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value65\" = Table.ReplaceValue(#\"Replaced Value64\",\"ผลิตถุงพลาสติก\",\"plastic bag production\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value66\" = Table.ReplaceValue(#\"Replaced Value65\",\"ทำเม็ดพลาสติกจากพลาสติกใช้แล้ว และบดย่อยพลาสติก\",\"Making plastic pellets from used plastic and crushing plastic\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value67\" = Table.ReplaceValue(#\"Replaced Value66\",\"ล้างและบดย่อยเศษพลาสติกและชิ้นส่วน\",\"Wash and shred plastic scraps and parts.\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value68\" = Table.ReplaceValue(#\"Replaced Value67\",\"ผลิตหินเทียม เช่น หินแกรนิต\",\"Artificial stone production such as granite\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Replaced Value69\" = Table.ReplaceValue(#\"Replaced Value68\",\"ผลิตปูนพลาสเตอร์\",\"plaster production\",Replacer.ReplaceText,{\"business (EN)\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Replaced Value69\",{\"Index\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Columns1\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"factory registration number\", \"FID factory registration code\", \"TSIC\", \"type code\", \"group\", \"licensed year\", \"factory name\", \"owner name\", \"business (TH)\", \"business (EN)\", \"number\", \"moo\", \"soi\", \"road\", \"sub-district\", \"district\", \"province code\", \"province\", \"post code\", \"telephone\", \"building value\", \"land value\", \"machine cost\", \"working capital\", \"total investment\", \"male\", \"female\", \"total workers\", \"total horsepower\", \"factory area (sq.m.)\", \"Building area (sq.m.)\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Reordered Columns2\",{{\"FID factory registration code\", type text}, {\"building value\", Int64.Type}, {\"land value\", Int64.Type}, {\"machine cost\", Int64.Type}, {\"working capital\", Int64.Type}, {\"total investment\", Int64.Type}, {\"male\", Int64.Type}, {\"female\", Int64.Type}, {\"total workers\", Int64.Type}, {\"total horsepower\", type number}, {\"factory area (sq.m.)\", Int64.Type}, {\"Building area (sq.m.)\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}